import { ArtistType } from '../sgh-domain/artist'

export const artists: ArtistType[] = [
  {
    name: 'i-COL',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/2.jpg', alt: '' },
    read: 'アイコル',
  },
  {
    name: 'iSPY',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/3.jpg', alt: '' },
    read: 'アイスパイ',
  },
  {
    name: 'ideal peco',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/92.jpg', alt: '' },
    read: 'アイデアルペコ',
  },
  {
    name: 'アイドルカレッジ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/5.jpg', alt: '' },
    read: 'アイドルカレッジ',
  },
  {
    name: 'I MY ME MINE',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/6.jpg', alt: '' },
    read: 'アイマイミーマイ',
  },
  {
    name: 'iLiFE!',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/7.jpg', alt: '' },
    read: 'アイライフ',
  },
  {
    name: 'iLiFE!候補生',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/8.jpg', alt: '' },
    read: 'アイライフコウホセイ',
  },
  {
    name: 'アキシブproject',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/9.jpg', alt: '' },
    read: 'アキシブプロジェクト',
  },
  {
    name: 'AQA',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/93.jpg', alt: '' },
    read: 'アクア',
  },
  {
    name: 'あくまで天使',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/94.jpg', alt: '' },
    read: 'アクマデテンシ',
  },
  {
    name: 'アステリア',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/155.jpg', alt: '' },
    read: 'アステリア',
  },
  {
    name: 'AdamLilith',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/95.jpg', alt: '' },
    read: 'アダン',
  },
  {
    name: 'UPローチ',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/96.jpg', alt: '' },
    read: 'アップ',
  },
  {
    name: 'アップアップガールズ（２）',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/10.jpg', alt: '' },
    read: 'アップアップガールズ（２）',
  },
  {
    name: 'アップアップガールズ（仮）',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/11.jpg', alt: '' },
    read: 'アップアップガールズ（仮）',
  },
  {
    name: 'AMOUR',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/97.jpg', alt: '' },
    read: 'アモーレ',
  },
  {
    name: 'Alcute！',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/12.jpg', alt: '' },
    read: 'アルキュート',
  },
  {
    name: 'アルテミスの翼',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/13.jpg', alt: '' },
    read: 'アルテミスのツバサ',
  },
  {
    name: 'alma',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/98.jpg', alt: '' },
    read: 'アルマ',
  },
  {
    name: 'THE ENCORE',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/25.jpg', alt: '' },
    read: 'アンコール',
  },
  {
    name: 'Ange☆Reve',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/14.jpg', alt: '' },
    read: 'アンジュレーブ',
  },
  {
    name: 'UNBS',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/99.jpg', alt: '' },
    read: 'アンビス',
  },
  {
    name: 'Waltetto×School',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/100.jpg', alt: '' },
    read: 'ヴァルテット',
  },
  {
    name: '泡沫パーティーズ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/15.jpg', alt: '' },
    read: 'ウタカタパーティーズ',
  },
  {
    name: 'SIR確変中',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/101.jpg', alt: '' },
    read: 'エスアイアール',
  },
  {
    name: 'えすれある',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/102.jpg', alt: '' },
    read: 'エスレアル',
  },
  {
    name: '【eN】',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/103.jpg', alt: '' },
    read: 'エン',
  },
  {
    name: 'ゑんら',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/91.jpg', alt: '' },
    read: 'エンラ',
  },
  {
    name: 'OS☆K',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/104.jpg', alt: '' },
    read: 'オーエスケー',
  },
  {
    name: 'OS☆U',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/105.jpg', alt: '' },
    read: 'オーエスユー',
  },
  {
    name: 'O2',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/106.jpg', alt: '' },
    read: 'オーツー',
  },
  {
    name: 'ガガピエロ',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/16.jpg', alt: '' },
    read: 'ガガピエロ',
  },
  {
    name: 'かすみ草とステラ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/17.jpg', alt: '' },
    read: 'カスミソウ',
  },
  {
    name: '仮面女子',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/18.jpg', alt: '' },
    read: 'カメンジョシ',
  },
  {
    name: 'カラフルスクリーム',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/19.jpg', alt: '' },
    read: 'カラフルスクリーム',
  },
  {
    name: 'カリスマめんざいふっ！',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/107.jpg', alt: '' },
    read: 'カリスマ',
  },
  {
    name: 'KissBee',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/108.jpg', alt: '' },
    read: 'キスビー',
  },
  {
    name: 'キミニハネ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/109.jpg', alt: '' },
    read: 'キミニハネ',
  },
  {
    name: '君に、胸キュン。',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/20.jpg', alt: '' },
    read: 'キミニムネキュン',
  },
  {
    name: '逆転ねこぱんちっ！',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/110.jpg', alt: '' },
    read: 'ギャクテン',
  },
  {
    name: 'CANDY TUNE',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/21.jpg', alt: '' },
    read: 'キャンディーチューン',
  },
  {
    name: '究極人形',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/111.jpg', alt: '' },
    read: 'キュウキョク',
  },
  {
    name: '九州女子翼',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/22.jpg', alt: '' },
    read: 'キュウシュウジョシリュウ',
  },
  {
    name: 'キュン!?恋堕ちキューピッド',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/112.jpg', alt: '' },
    read: 'キュンコイオチ',
  },
  {
    name: 'GILTY×GILTY',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/23.jpg', alt: '' },
    read: 'ギルティギルティ',
  },
  {
    name: 'Glim Assembler',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/160.jpg', alt: '' },
    read: 'グリムアセンブラー',
  },
  {
    name: 'KRD8',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/113.jpg', alt: '' },
    read: 'ケーアール',
  },
  {
    name: 'けっぱって東北',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/114.jpg', alt: '' },
    read: 'ケッパッテ',
  },
  {
    name: 'SAI²Rium',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/161.jpg', alt: '' },
    read: 'サイサイリウム',
  },
  {
    name: 'サクヤコノハナ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/24.jpg', alt: '' },
    read: 'サクヤコノハナ',
  },
  {
    name: 'C;ON',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/115.jpg', alt: '' },
    read: 'シーオン',
  },
  {
    name: 'シークレットシャノワール',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/26.jpg', alt: '' },
    read: 'シークレットシャノワール',
  },
  {
    name: 'ジエメイ',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/27.jpg', alt: '' },
    read: 'ジエメイ',
  },
  {
    name: 'Sistersあにま',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/116.jpg', alt: '' },
    read: 'シスターズアニマ',
  },
  {
    name: 'SITRA.',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/117.jpg', alt: '' },
    read: 'シトラ',
  },
  {
    name: 'JAPANARIZM',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/29.jpg', alt: '' },
    read: 'ジャパナリズム',
  },
  {
    name: 'Sharply♯ × Flutter♭',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/28.jpg', alt: '' },
    read: 'シャプフラ',
  },
  {
    name: 'JamsCollection',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/30.jpg', alt: '' },
    read: 'ジャムズコレクション',
  },
  {
    name: 'Shupines',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/118.jpg', alt: '' },
    read: 'シュピネス',
  },
  {
    name: 'シュレーディンガーの犬',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/31.jpg', alt: '' },
    read: 'シュレディンガー',
  },
  {
    name: '純情のアフィリア',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/32.jpg', alt: '' },
    read: 'ジュンジョウノアフィリア',
  },
  {
    name: 'しろもん',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/119.jpg', alt: '' },
    read: 'シロモン',
  },
  {
    name: '神使轟く、激情の如く。',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/33.jpg', alt: '' },
    read: 'シンシゴトク',
  },
  {
    name: 'シンデレラ宣言！',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/34.jpg', alt: '' },
    read: 'シンデレラセンゲン',
  },
  {
    name: 'Symdolick',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/35.jpg', alt: '' },
    read: 'シンドリック',
  },
  {
    name: '彗星♩droptune°',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/157.jpg', alt: '' },
    read: 'スイセイドロップチューン',
  },
  {
    name: 'Sweet Alley',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/36.jpg', alt: '' },
    read: 'スウィートアレイ',
  },
  {
    name: 'すーぱーぷーばぁー!!',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/120.jpg', alt: '' },
    read: 'スーパープー',
  },
  {
    name: '夜宙☆ShiNew’',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/156.jpg', alt: '' },
    read: 'スターシャイニュー',
  },
  {
    name: 'すたんぴっ！',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/121.jpg', alt: '' },
    read: 'スタンピ',
  },
  {
    name: 'ZUTTOMOTTO',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/37.jpg', alt: '' },
    read: 'ズットモット',
  },
  {
    name: 'SPRISE',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/38.jpg', alt: '' },
    read: 'スプライズ',
  },
  {
    name: 'スポポポポニー',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/39.jpg', alt: '' },
    read: 'スポポポポニー',
  },
  {
    name: 'SAY-LA',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/122.jpg', alt: '' },
    read: 'セイラ',
  },
  {
    name: 'SAISON',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/40.jpg', alt: '' },
    read: 'セゾン',
  },
  {
    name: 'Cent Heaven',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/123.jpg', alt: '' },
    read: 'セントヘブン',
  },
  {
    name: 'タイトル未定',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/41.jpg', alt: '' },
    read: 'タイトルミテイ',
  },
  {
    name: 'Task have Fun',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/42.jpg', alt: '' },
    read: 'タスクハブファン',
  },
  {
    name: 'W.ダブルヴィ一',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/43.jpg', alt: '' },
    read: 'ダブルウィー',
  },
  {
    name: 'Chu-Z',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/44.jpg', alt: '' },
    read: 'チューズ',
  },
  {
    name: 'twinpale',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/45.jpg', alt: '' },
    read: 'ツインペイル',
  },
  {
    name: '月に足跡を残した6人の少女達は一体何を見たのか...',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/124.jpg', alt: '' },
    read: 'ツキニアシアト',
  },
  {
    name: 'TEARS-ティアーズ-',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/125.jpg', alt: '' },
    read: 'ティアーズ',
  },
  {
    name: '手羽先センセーション',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/46.jpg', alt: '' },
    read: 'テバサキ',
  },
  {
    name: 'dela',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/47.jpg', alt: '' },
    read: 'デラ',
  },
  {
    name: 'テラス×テラス',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/126.jpg', alt: '' },
    read: 'テラス×テラス',
  },
  {
    name: '天使にはなれない',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/127.jpg', alt: '' },
    read: 'テンシニハ',
  },
  {
    name: 'テンシメシ',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/48.jpg', alt: '' },
    read: 'テンシメシ',
  },
  {
    name: '点染テンセイ少女。',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/49.jpg', alt: '' },
    read: 'テンセンテンセイ',
  },
  {
    name: 'TENRIN',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/50.jpg', alt: '' },
    read: 'テンリン',
  },
  {
    name: '東京CuteCute',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/128.jpg', alt: '' },
    read: 'トウキョウ',
  },
  {
    name: '東京ガールズブラボー',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/51.jpg', alt: '' },
    read: 'トウキョウガールズブラボー',
  },
  {
    name: '2o Love to Sweet Bullet',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/52.jpg', alt: '' },
    read: 'トュラブ',
  },
  {
    name: 'DREAMING MONSTER',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/129.jpg', alt: '' },
    read: 'ドリーミング',
  },
  {
    name: '#ドレミファソラシード',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/53.jpg', alt: '' },
    read: 'ドレミファ',
  },
  {
    name: 'ナト☆カン',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/158.jpg', alt: '' },
    read: 'ナトカン',
  },
  {
    name: 'ナナコロビヤオキ',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/130.jpg', alt: '' },
    read: 'ナナコロビ',
  },
  {
    name: 'ナナランド',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/54.jpg', alt: '' },
    read: 'ナナランド',
  },
  {
    name: 'なみだ色の消しごむ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/55.jpg', alt: '' },
    read: 'ナミダイロ',
  },
  {
    name: 'なんキニ！',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/56.jpg', alt: '' },
    read: 'ナンキニ',
  },
  {
    name: '#2i2',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/57.jpg', alt: '' },
    read: 'ニイニ',
  },
  {
    name: '虹色の飛行少女',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/58.jpg', alt: '' },
    read: 'ニジイロ',
  },
  {
    name: 'にっぽんワチャチャ',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/59.jpg', alt: '' },
    read: 'ニッポンワチャチャ',
  },
  {
    name: 'にとくり。',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/131.jpg', alt: '' },
    read: 'ニトクリ',
  },
  {
    name: 'NEO BREAK',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/132.jpg', alt: '' },
    read: 'ネオブレイク',
  },
  {
    name: '脳内パステル',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/60.jpg', alt: '' },
    read: 'ノウナイ',
  },
  {
    name: 'のんふぃく！',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/61.jpg', alt: '' },
    read: 'ノンフィク',
  },
  {
    name: 'HIGH SPIRITS',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/62.jpg', alt: '' },
    read: 'ハイスピリッツ',
  },
  {
    name: '蜂蜜★皇帝',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/133.jpg', alt: '' },
    read: 'ハチミツ',
  },
  {
    name: '花いろは',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/63.jpg', alt: '' },
    read: 'ハナイロハ',
  },
  {
    name: 'ハニースパイスRe.',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/65.jpg', alt: '' },
    read: 'ハニースパイス',
  },
  {
    name: 'Panic Monster !n Wonderland',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/66.jpg', alt: '' },
    read: 'パニックモンスター',
  },
  {
    name: '蜜兎',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/134.jpg', alt: '' },
    read: 'ハニバニ',
  },
  {
    name: 'Bunny La Crew',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/64.jpg', alt: '' },
    read: 'バニラクルー',
  },
  {
    name: '#ババババンビ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/67.jpg', alt: '' },
    read: 'ババババンビ',
  },
  {
    name: 'パラディーク',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/135.jpg', alt: '' },
    read: 'パラディーク',
  },
  {
    name: 'Palette Parade',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/68.jpg', alt: '' },
    read: 'パレットパレード',
  },
  {
    name: 'Peel the Apple',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/69.jpg', alt: '' },
    read: 'ピールジ',
  },
  {
    name: 'P-Loco',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/136.jpg', alt: '' },
    read: 'ピーロコ',
  },
  {
    name: 'ヒトノユメ',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/137.jpg', alt: '' },
    read: 'ヒトノユメ',
  },
  {
    name: 'FES☆TIVE',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/70.jpg', alt: '' },
    read: 'フェスティブ',
  },
  {
    name: 'フューチャーサイダー',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/71.jpg', alt: '' },
    read: 'フューチャーサイダー',
  },
  {
    name: 'Blancanie',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/138.jpg', alt: '' },
    read: 'ブランカニエ',
  },
  {
    name: 'PrincessGarden-Nagoya-',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/139.jpg', alt: '' },
    read: 'プリンセスガーデンナゴヤ',
  },
  {
    name: 'PrincessGarden-姫庭-',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/72.jpg', alt: '' },
    read: 'プリンセスガーデンヒメニワ',
  },
  {
    name: 'フルーティー',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/73.jpg', alt: '' },
    read: 'フルーティー',
  },
  {
    name: 'ベロティカ',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/140.jpg', alt: '' },
    read: 'ベロティカ',
  },
  {
    name: 'ベンジャス！',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/74.jpg', alt: '' },
    read: 'ベンジャス',
  },
  {
    name: 'ポラライト',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/163.jpg', alt: '' },
    read: 'ポラライト',
  },
  {
    name: 'ポンコツコンポ',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/75.jpg', alt: '' },
    read: 'ポンコツコンボ',
  },
  {
    name: 'マーキュロ',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/141.jpg', alt: '' },
    read: 'マーキュロ',
  },
  {
    name: 'My Sugar Light',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/142.jpg', alt: '' },
    read: 'マイシュガー',
  },
  {
    name: 'MyDearDarlin’',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/76.jpg', alt: '' },
    read: 'マイディア',
  },
  {
    name: 'マイノリティアラート',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/143.jpg', alt: '' },
    read: 'マイノリティアラート',
  },
  {
    name: 'MATANAGOYA',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/144.jpg', alt: '' },
    read: 'マタナゴヤ',
  },
  {
    name: '真っ白なキャンバス',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/77.jpg', alt: '' },
    read: 'マッシロナ',
  },
  {
    name: 'まねきケチャ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/78.jpg', alt: '' },
    read: 'マネキケチャ',
  },
  {
    name: '瞬きもせず',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/145.jpg', alt: '' },
    read: 'マバタキモセズ',
  },
  {
    name: 'ミスティア！',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/146.jpg', alt: '' },
    read: 'ミスティア',
  },
  {
    name: 'mistress',
    day1: true,
    day2: false,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/79.jpg', alt: '' },
    read: 'ミストレす',
  },
  {
    name: 'ミラクルファンファーレ！',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/147.jpg', alt: '' },
    read: 'ミラクルファンファーレ！',
  },
  {
    name: 'Milky＊Sphene',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/148.jpg', alt: '' },
    read: 'ミルキー',
  },
  {
    name: '#Mooove!',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/80.jpg', alt: '' },
    read: 'ムーブ',
  },
  {
    name: 'メイビーME',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/81.jpg', alt: '' },
    read: 'メイビーミー',
  },
  {
    name: 'モノクローン',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/82.jpg', alt: '' },
    read: 'モノクローん',
  },
  {
    name: 'もふる×クロス',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/149.jpg', alt: '' },
    read: 'モフルクロス',
  },
  {
    name: '夜光性アミューズ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/83.jpg', alt: '' },
    read: 'ヤコウセイ',
  },
  {
    name: 'ヤンチャン学園音楽部',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/159.jpg', alt: '' },
    read: 'ヤンチャン',
  },
  {
    name: '#よーよーよー',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/84.jpg', alt: '' },
    read: 'ヨーヨーヨー',
  },
  {
    name: 'LOVE 9 LOVE',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/150.jpg', alt: '' },
    read: 'ラブクラブ',
  },
  {
    name: 'LOVEME',
    day1: false,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/162.jpg', alt: '' },
    read: 'ラブミー',
  },
  {
    name: '愛乙女☆DOLL(チームL)',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/4.jpg', alt: '' },
    read: 'ラブリードール',
  },
  {
    name: 'Re:Clash(Candy☆Drops)',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/151.jpg', alt: '' },
    read: 'リクラッシュ',
  },
  {
    name: 'ЯiＭ：ＭiＲ',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/85.jpg', alt: '' },
    read: 'リミー',
  },
  {
    name: 'Lily wonder',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/152.jpg', alt: '' },
    read: 'リリーワンダー',
  },
  {
    name: 'RiNCENT#',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/86.jpg', alt: '' },
    read: 'リンセント',
  },
  {
    name: 'ルルネージュ',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/87.jpg', alt: '' },
    read: 'ルルネージュ',
  },
  {
    name: 'READY TO KISS',
    day1: false,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/153.jpg', alt: '' },
    read: 'レディー',
  },
  {
    name: 'Le☆miel',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/154.jpg', alt: '' },
    read: 'レミール',
  },
  {
    name: 'ワンダーウィード 天',
    day1: true,
    day2: true,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/88.jpg', alt: '' },
    read: 'ワンダーウィード',
  },
  {
    name: 'わんふぁす！',
    day1: false,
    day2: false,
    day3: true,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/89.jpg', alt: '' },
    read: 'ワンファス',
  },
  {
    name: 'Onephony',
    day1: true,
    day2: true,
    day3: false,
    img: { src: 'https://sekigahara-idolwars.net/images/2024/artists/90.jpg', alt: '' },
    read: 'ワンフォニー',
  },
]
