import { UnitProps } from '@/templates/unitBox'

export const artists: UnitProps[] = [
  {
    name: 'ゆにきゅーと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ゆにきゅーと.png',
      alt: 'ゆにきゅーと',
    },
    content: '可愛い唯一の存在。エネルギッシュのあるライブで皆さんを楽しませます！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/unicute131.mov',
    x: 'unicute131',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: 'BrainBeat',
    yomi: 'ぶれいんびーと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/BrainBeat.jpg',
      alt: 'BrainBeat',
    },
    content:
      'BrainBeatは、\“ピュア×ギャル\”というアンビバレントな魅力を武器に、「どんな困難にも抗い、何度でもステージへ、何度でも前へ」を掲げて活動するアイドルグループです。<br />2025年1月31日に始動。現在は、ぽれあ・ひな・さやの3名を中心に活動しております。ユーロビートや重低音を軸とした高揚感ある楽曲と、熱量でフロアを巻き込むライブを強みとして、一つひとつのステージを積み重ねてまいりました。<br /> <br/>決して平坦ではない道のりの中でも立ち止まらず、自分たちの“好き”と覚悟で前に進み続けていることが、今のBrainBeatの一番の核です。<br />そして関ケ原唄姫合戦は、グループ結成時から思い描いてきた夢の舞台の一つでもあります。<br /><br />この予戦会もただの挑戦ではなく、本気で夏へつなげるための勝負の場だと思っております。<br/>一度見たら忘れられない熱量で「このグループを本戦で見たい」と思っていただけるライブをお届けいたします！',
    x: 'brainbeat_idol',
    insta: '',
    tiktok: 'https://www.tiktok.com/@brainbeat_',
    other: 'https://maux.jp/artist.html',
  },
  {
    name: 'ADMIRAL×BANQUET',
    yomi: 'アドミラルバンケット',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ADMIRAL×BANQUET.png',
      alt: 'ADMIRAL×BANQUET',
    },
    content:
      '2025.7.17デビュー。<br />『統率せよ、心を。魅了せよ、世界を。』<br /><br/>2026.2.10に渋谷Starlougeで開催した1stワンマンライブは満員を達成。<br /><br />アドバンならではの規格外の楽曲クオリティで、近年のアイドルシーンへ鋭く切り込む。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/adban_official.mov',
    x: 'adban_official',
    insta: '',
    tiktok: 'https://www.tiktok.com/@adban_official?_r=1&_t=ZS-95gkIl8l8Hl',
    other: 'https://www.tunecore.co.jp/artists/admiralbanquet',
  },
  {
    name: 'Nody',
    yomi: 'のーでぃー',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Nody.jpg',
      alt: 'Nody',
    },
    content:
      'コンセプト:ハイパーメロウポップアイドル<br />活動期間:2024.5.30〜<br />実績:2025.5.29 1周年単独公演梅田クアトロ実施<br />来月5/29に単独公演心斎橋BIGCAT公演開催',
    x: 'no_day_official',
    insta: '',
    tiktok: 'https://www.tiktok.com/@no_dy_official?_r=1&_t=ZS-95gsFBtdQCi',
    other: 'https://lit.link/nodayofficial2024',
  },
  {
    name: 'めろでぃらびっと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/めろでぃらびっと.png',
      alt: 'めろでぃらびっと',
    },
    content:
      '2026年4月19日にデビューした、元LOVE9LOVE「おうかなつ」プロデュースの関西エリアで活動しているアイドルグループになります。<br />アイドルオタクアイドルとして活動していた「おうかなつ」の経験を基に集まった全員前世無し未経験者で揃った可愛らしい王道系７人組のグループです。<br />関西人らしい明るいキャラで可愛さをお届け出来るように頑張ります。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/melorabbi.mov',
    x: 'melorabbi',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: 'IDOL★ST∀R MINE',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/IDOL★ST∀R MINE.jpg',
      alt: 'IDOL★ST∀R MINE',
    },
    content:
      '2020年2月デビュー。今年3/29のワンマンライブで研究生2名が昇格し全員正規メンバーの6人体制に。<br />昨年9月より冠ラジオ番組「IDOL★ST∀R MINEのIDOL★SPark Radio」を毎月第１月曜日20:30から30分間MID-FM76.1にて放送中。<br />関ケ原唄姫合戦には2021,2022,2023年に出演！<br />今回、メンバーが増えて今の6人で挑戦したいと思い、3年ぶりの予戦会参加です！<br /><br />メンバー：雅ことめ（赤色）・結夢かえ（黄色）・陽翠はつき（白色）・神凪桃亜（ピンク色）・佐条菖（紫色）・橘羽うか（水色）',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/IDOL_STAR_MINE.mov',
    x: 'IDOL_STAR_MINE',
    insta: '',
    tiktok: '',
    other: 'https://philosophia-ent.com/',
  },
  {
    name: 'Harley Queen',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Harley Queen.jpg',
      alt: 'Harley Queen',
    },
    content:
      '2021年4月29日に結成し、2023年12月30日の活動休止を経て、<br />2025年9月13日に事務所移転も伴い、新たな気持ちで活動開始しました。<br />HarleyQueenはステージと客席が一体となって盛り上がることのできるライブパフォーマンスが最大の魅力です。<br />是非、ライブで声を出したり、一緒に踊ったりしてください！<br />暑い夏に熱いパフォーマンスを届けたいので応援よろしくお願い致します！<br /><br />メンバー<br />北川らん<br />担当カラー：青色<br />Xアカウント：@Harley_Ran<br /><br />水城かぐや<br />担当カラー：赤色<br />Xアカウント：@harley_kaguya<br /><br />卯月えり<br />担当カラー：白色<br />Xアカウント：@Harley_eri_',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/Harley_Queen_3.mp4',
    x: 'Harley_Queen_3',
    insta: '',
    tiktok: '',
    other: 'https://timetreeapp.com/public_calendars/harleyqueen',
  },
  {
    name: 'わんみゅーず！',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/わんみゅーず！.png',
      alt: 'わんみゅーず！',
    },
    content:
      '2025年12月12日デビュー！<br />大阪拠点 テーマパークコンセプトのわんみゅーず！です！<br />メロディレッド担当 甘苺るう (あまいるう)<br />ときめきぴんく担当 兎月みあい (うづきみあい)<br />レモネードイエロー担当 日奈こゆ (ひなこゆ)<br />わがままぱーぷる担当 天和あもね (てんのあもね)<br />わたあめらいとぶるー担当 空音りのん (そらねりのん)<br />3月16日に追加メンバーとなった<br />おこじょほわいと担当 柊羽夏 (ひいらぎはな)<br /><br />からなる6人組アイドルグループ！<br />アー写のデザイン制作から加工編集、衣装デザイン、イベントフライヤー、チェキ券やグッズイラストやデザイン、曲の作詞等 18歳の甘苺るうが全て制作しプロデュースしています。<br /><br />歌担当やダンス担当、可愛い担当や美人で推したいお笑い(？！)担当、人類の垣根を越える奇想天外担当など<br />1人残らず個性が強すぎる仲良しグループ！<br />個人の個性に限らず楽曲もいろんなジャンルが楽しめます！<br /><br />テレビ大阪主催「はばたけアイドルフェス」シリーズにも出演<br /><br />今回初めての大きな舞台への挑戦です！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/onemuseofficial.mp4',
    x: 'onemuseofficial',
    insta: '@onemuse_official',
    tiktok: '@onemuseofficial',
    other: 'https://lit.link/onemuse',
  },
  {
    name: 'オトメルキュール',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/オトメルキュール.jpeg',
      alt: 'オトメルキュール',
    },
    content:
      '2024年6月デビュー『かわいいだけじゃない！』をコンセプトに多彩な楽曲でステージパフォーマンスを重視した5人組の王道アイドルグループ。<br />グループ名は音＋乙女＋メルキュール（水星）3つの言葉を重ねた『オトメルキュール』',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/otomercure.mp4',
    x: 'otomercure',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: 'POPING CANDY.',
    yomi: 'ぽぴんぐきゃんでぃ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/POPING CANDY..jpeg',
      alt: 'POPING CANDY.',
    },
    content:
      'コンセプト<br /><strong>POPING CANDY.（ぽぴんぐきゃんでぃ）</strong>は、<br />“あまくて はじける”をコンセプトに活動する3人組キャンディ系アイドルグループ🍬✨<br /><br />ライブも、日常も、ときめきに変えていく——<br /><br /><strong>「君と一緒に弾け飛ぶ！」</strong>を合言葉に、<br /><br />見た人の心を甘くPOPに彩ります💫<br /><br /><br />活動開始日<br /><br />プレデビュー : 2024/12/1<br /><br />デビュー : 2025/10/5<br /><br />メンバー紹介<br /><br />・黒沢凪　ブルーハワイキャンディ担当<br />・来餅いの　レモネードキャンディ担当<br />・藤咲める　グレープヨーグルトキャンディ担当',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/POPINGCANDY_gf.mov',
    x: 'POPINGCANDY_gf',
    insta: '',
    tiktok: 'https://www.tiktok.com/@popingcandy_gf',
    other: 'https://popingcandygf.wixsite.com/popingcandy',
  },
  {
    name: 'にとくり。',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/にとくり。.png',
      alt: 'にとくり。',
    },
    content:
      '王道×清楚系をコンセプトに、爽やかで甘酸っぱい楽曲からキャッチーで盛り上がる楽曲まで幅広いパフォーマンスが見所です！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/Neatandclean727.mp4',
    x: 'Neatandclean727',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: 'anemoreel',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/anemoreel.jpeg',
      alt: 'anemoreel',
    },
    content:
      '2025年11月3日、心斎橋VARONにて3組での対バン形式でデビューライブを開催。約170名動員。<br /><br/>平均年齢20才、平均身長152cm。<br /><br/>大阪を拠点として活動している7人組アイドルグループ。<br /><br/>「どこか懐かしい青春と思い出を」をコンセプトとして、片想いの歌詞や初々しい恋愛曲を中心に爽やかなイメージで活動しています。<br /><br/>爽やかで清楚な世界観を軸にしながらも、ライブでは明るくエネルギッシュなメンバーが全力でパフォーマンスする“清楚×シャカリキ”なギャップが武器です。<br /><br/>3月から定期公演、5月には大阪MUSEにて半年ワンマン、11月にバナナホールにて一周年ワンマンを開催予定です。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/anemoreel.mp4',
    x: 'anemoreel',
    insta: '@anemoreel_official',
    tiktok: '@anemoreel',
    other: '',
  },
  {
    name: 'SANUGLOW',
    yomi: 'サンヌグロウ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/SANUGLOW.jpeg',
      alt: 'SANUGLOW',
    },
    content:
      'コンセプト『輝きを、繰り返す。』<br />活動開始は2024/11/29<br /><br />メンバー紹介<br />①紫色担当💜<br />紫雅楽ひとり(しがらきひとり)<br /><br />②白色担当🤍<br />他愛もある(たあいもある)<br /><br />③青色担当💙<br />王様ゆう(きんぐゆう)<br /><br />④水色担当🩵<br />琥翔なの(たいがなの)<br /><br /><br />2024年11月29日にFANJ twiceにてデビュー。<br />2026年3月15日には名古屋進出も視野に入れ、止まることなく展開を広げるSANUGLOW。<br />2025年11月29日の1周年ワンマンを経て、2026年4月15日には1.5周年ワンマンをOSAKA MUSEで開催し、会場を熱狂で埋め尽くしました。確かな勢いと存在感でファンを魅了しながら、さらなる高みへと歩みを進めています。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/SANUGLOW.mp4',
    x: 'SANUGLOW',
    insta: '@sanuglow_official',
    tiktok: '@sanuglow',
    other: '',
  },
  {
    name: 'ひとつキラリ',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ひとつキラリ.jpeg',
      alt: 'ひとつキラリ',
    },
    content:
      'キラリと光る、たった一つの誇りになりたい。<br />あなたのために、WONDER CUTENESS OVERLOAD!!【奇跡の可愛さがすぎる】<br /><br />活動開始日<br />2025年2月24日<br /><br />メンバー紹介<br />如月蓮華　【赤】 グループ唯一の金髪ぎゃる<br />七宮夜々　【黄色】天真爛漫わがままムードメーカー<br />時禾ろり　【ピンク】 <br />キラリの煽り担当甘えん坊わんちゃん<br />月下恋　【水色】 踊れるほんわかよちよちペンギン<br />リア　【白】 韓国から来たあざといお姫ちゃま<br />爽音ひなた　【青】キラリの朝の顔、爽やかダンサー！<br /><br />実績<br />2025年 関ケ原唄姫合戦 予戦会突破・出場',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/hitotsukirari.mp4',
    x: 'hitotsukirari',
    insta: '',
    tiktok: '',
    other: 'https://youtube.com/channel/UCny3YZG9GYJmIfQaalQKUdQ?si=L8ZWXwSLIff5sKvS',
  },
  {
    name: 'Coloration',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Coloration.jpeg',
      alt: 'Coloration',
    },
    content:
      '2025年2月27日デビュー、「心に溶け込む彩りに」をコンセプトに東京拠点で活動してる正統派王道アイドルグループです。<br /><br />Colorationメンバー<br />・有明つき  (ありあけつき)<br />メンバーカラー：オレンジ<br />出身地：三重県<br />・篠宮きき (しのみやきき)<br />メンバーカラー：イエロー<br />出身地：神奈川県<br />・花園もえ (はなぞのもえ)<br />メンバーカラー：ライトブルー<br />出身地：大阪府<br />・藤咲ゆら(ふじさきゆら)<br />メンバーカラー：パープル<br />出身地：静岡県',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/coloration_n.mp4',
    x: 'coloration_n',
    insta: 'https://www.instagram.com/coloration_n?igsh=MWVibjc2OTlpYnFsYw==',
    tiktok: 'https://www.tiktok.com/@coloration_n?_r=1&_t=ZS-9344H6D7UIa',
    other: 'https://youtube.com/@coloration_n?si=AxNk8P2y4NWBVEFM',
  },
  {
    name: 'ラビットビット',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ラビットビット.jpg',
      alt: 'ラビットビット',
    },
    content:
      'コールボードを持ったパフォーマンスを行います！<br />オタ芸・デコトラ運転手・ひき肉料理の使い手・保育士・心霊スポットの住人の5人組で活動しております！<br /><br />今年も暑い夏をさらに熱くしていきます！！',
    movie: '',
    x: 'rabbitbit2022',
    insta: 'https://www.instagram.com/rabbitbit2022/',
    tiktok: 'https://www.tiktok.com/@usa_chans',
    other: '',
  },
  {
    name: 'melnoir',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/melnoir.jpeg',
      alt: 'melnoir',
    },
    content:
      '『あなたの孤独や不安を溶かし虜にする』をコンセプトに活動している2026.2.19デビューの5人組アイドルグループ<br /><br />赤担当 愛河せいら<br />ピンク担当 恋猫える<br />水色担当 乙月あかり<br />オレンジ担当 陽咲あゆら<br />紫担当 かなみとま',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/melnoir_.mov',
    x: 'melnoir_',
    insta: '',
    tiktok: '@melnoir_info',
    other: '',
  },
  {
    name: 'ラルムストーン',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ラルムストーン.png',
      alt: '',
    },
    content:
      '【コンセプト】  <br />出会った瞬間、恋に落ちる儚い宝石<br /><br />【デビュー】  <br />2026年1月28日 赤羽ReNY alpha<br /><br />【メンバー】  <br />・ピーチクォーツ担当　桃月莉妃（ももつき りこ）  <br />・ルビーレッド担当　望乃愛叶（のぞの あいか）  <br />・エメラルドグリーン担当　涼波碧璃（すずなみ あおり）  <br />・アメジストラベンダー担当　来未かりん（くるみ かりん）  <br />・アイスブルー担当　水城れな（みずしろ れな）  <br /><br />※6人で活動しております。<br /><br />【プロデュース】  <br />元AKB48 宮里莉羅 完全プロデュース<br /><br />【グループについて】  <br />元SKE48として活動していたメンバーをはじめ、アイドル初挑戦のメンバーも多く、初々しさと真っ直ぐな想いを胸に活動しています。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/larmestone.mov',
    x: 'larmestone',
    insta: '',
    tiktok: 'https://www.tiktok.com/@larmestone?_r=1&_t=ZS-95fEPnY9qPn',
    other: '',
  },
  {
    name: 'Squall Line',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Squall Line.jpg',
      alt: 'Squall Line',
    },
    content:
      'きらめく雨粒は、やがて心を打つスコールへ。<br /><br />メンバー：柴山ゆち、東雲きゃん、神楽まつり、兎咲とうか、そして5月より月守ゆらを新メンバーに加え<br />更に勢いを増す、関西拠点の正統派アイドルユニットです。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/squallline_oa.mov',
    x: 'squallline_oa',
    insta: '',
    tiktok: '',
    other: 'https://lit.link/squallline_oa',
  },
  {
    name: 'image',
    yomi: 'いまーじゅ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/image.jpeg',
      alt: 'image',
    },
    content:
      '2025年3月20日にデビューした名古屋発<br />5人組アイドルグループ「image」<br />コンセプト“emotional × パフォーマンス”。感情を揺さぶる表現力と、一体感あるステージを大切にライブをしています。<br />メンバーそれぞれの個性や魅力を発揮しながら、グループとしての完成度を追求し続けており、ビジュアル面・パフォーマンス面の両立を目指し日々努力を重ねています。<br /><br />実績 <br />2025 3月20日 伏見ライオンシアター 単独公演デビュー <br />2025 9月22日 大須X-HALL 1stワンマンライブ <br />2026 3月27日 名古屋Reny Limited 2nd ワンマンライブ<br /><br />メンバー<br />子守なの(ミントグリーン担当)<br />有栖れな(ピンク色担当)<br />生駒もも(黄色担当)<br />白雪りか(白色担当)<br />夜空しづき(赤色担当)',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/image__official.mov',
    x: 'image__official',
    insta: 'https://www.instagram.com/fleur_info?igsh=cmJjdG92NjNjYngx&utm_source=qr',
    tiktok: 'https://www.tiktok.com/@imageofficial.love?_r=1&_t=ZS-95Y9lWAIonR',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
  {
    name: '',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/.jpeg',
      alt: '',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
  },
]
