import { UnitProps } from '@/templates/unitBox'

export const artists: UnitProps[] = [
  {
    name: 'AiMEL!!-あいめる-【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/AiMEL!!-あいめる-.jpg',
      alt: 'AiMEL!!-あいめる-',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'eAPPfu1xaOU7kkY4X8ZSfzYoB813',
  },
  {
    name: "I's Merry Go Round【未提出】",
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/I_s Merry Go Round.jpeg',
      alt: 'I_s Merry Go Round',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'lNfjJi4W4JXKat6hbQ9eBVYEFE72',
  },
  {
    name: 'IDOL★ST∀R MINE',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/IDOL★ST∀R MINE.jpg',
      alt: 'IDOL★ST∀R MINE',
    },
    content:
      '2020年2月デビュー。今年3/29のワンマンライブで研究生2名が昇格し全員正規メンバーの6人体制に。<br />昨年9月より冠ラジオ番組「IDOL★ST∀R MINEのIDOL★SPark Radio」を毎月第１月曜日20:30から30分間MID-FM76.1にて放送中。<br />関ケ原唄姫合戦には2021,2022,2023年に出演！<br />今回、メンバーが増えて今の6人で挑戦したいと思い、3年ぶりの予戦会参加です！<br /><br />メンバー：雅ことめ（赤色）・結夢かえ（黄色）・陽翠はつき（白色）・神凪桃亜（ピンク色）・佐条菖（紫色）・橘羽うか（水色）',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/IDOL_STAR_MINE.mov',
    x: 'IDOL_STAR_MINE',
    insta: '',
    tiktok: '',
    other: 'https://philosophia-ent.com/',
    withColle: 'UxFVyixVQQcMhDvRXrem2MB6LLh1',
  },
  {
    name: 'ADMIRAL×BANQUET',
    yomi: 'アドミラルバンケット',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ADMIRAL×BANQUET.png',
      alt: 'ADMIRAL×BANQUET',
    },
    content:
      '2025.7.17デビュー。<br />『統率せよ、心を。魅了せよ、世界を。』<br /><br/>2026.2.10に渋谷Starlougeで開催した1stワンマンライブは満員を達成。<br /><br />アドバンならではの規格外の楽曲クオリティで、近年のアイドルシーンへ鋭く切り込む。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/adban_official.mov',
    x: 'adban_official',
    insta: '',
    tiktok: 'https://www.tiktok.com/@adban_official?_r=1&_t=ZS-95gkIl8l8Hl',
    other: 'https://www.tunecore.co.jp/artists/admiralbanquet',
    withColle: 'Pn5x5zohhkNebKgzau5CDetzvh33',
  },
  {
    name: 'あもるてぃえ',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/あもるてぃえ.png',
      alt: 'あもるてぃえ',
    },
    content:
      'パティシエール、お菓子をコンセプトにした4人組グループです。<br /><br />「お菓子を作るように自分たちの手で道を作っていきたい」という思いが込められています。<br /><br />お菓子のような甘さを連想する楽曲が多い中でビターでダークな一面も！？<br /><br />令和の時代に平成っぽさをのこしつつ私たちの可愛さで甘い空間を作っていきます。<br /><br /><br /><br />あもるてぃえは2026年5月にデビューしたばかり<br /><br />関ヶ原唄姫合戦予選はあもるてぃえにとって大きな挑戦です。<br /><br />ここから道が開けますように。<br /><br />私たちの本気をぶつけさせてください。<br /><br /><br /><br /><strong>メンバー紹介</strong><br /><br />🍬夢原すみれ（ゆめはらすみれ）<br /><br />キャンディー担当<br /><br />あもるてぃえのリーダー<br /><br />ペンライトは紫<br /><br />身長は146cm<br /><br />「小さくても誰よりもコールを先導して熱いステージにします！」<br /><br /><br />🍩白浜いるか（しらはまいるか）<br /><br />ドーナッツ担当<br /><br />あもるてぃえの元気担当<br /><br />ペンライトはよくばりオーシャンブルー！<br /><br />「夏といえばアイドル！夏といえば関ヶ原唄姫合戦！絶対に熱い夏にします！」<br /><br /><br />🍫月澪りる（つきみおりる）<br /><br />チョコレート担当<br /><br />あもるてぃえのお姉さん<br /><br />ペンライトは黄色<br /><br />沖縄出身<br /><br />「大きな挑戦となりますがメンバーとファンの皆さんと力を合わせて目標を達成できるように最大限の努力をします！絶対に楽しい夏にします！」<br /><br /><br />🍪栗野ゆゆ（くりのゆゆ）<br /><br />クッキー担当<br /><br />あもるてぃえの最年少<br /><br />ペンライトは緑<br /><br />「去年までは１ファンとしてアイドルを見ていました。憧れのステージに絶対に立ちます！応援よろしくお願いします」<br /><br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/amortier_.mov',
    x: 'amortier_',
    insta: 'https://www.instagram.com/amortier_?igsh=MTUxZXYxMXBhOW9yNw%3D%3D&utm_source=qr',
    tiktok: 'https://www.tiktok.com/@_amortier_?_r=1&_t=ZS-95c7yL4m5cV',
    other: '',
    withColle: 'SkTqLAFMV6eRFapDvp51xw4B2ft1',
  },
  {
    name: 'anemoreel',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/anemoreel.jpeg',
      alt: 'anemoreel',
    },
    content:
      '2025年11月3日、心斎橋VARONにて3組での対バン形式でデビューライブを開催。約170名動員。<br /><br />平均年齢20才、平均身長152cm。<br /><br />大阪を拠点として活動している7人組アイドルグループ。<br /><br />「どこか懐かしい青春と思い出を」をコンセプトとして、片想いの歌詞や初々しい恋愛曲を中心に爽やかなイメージで活動しています。<br /><br />爽やかで清楚な世界観を軸にしながらも、ライブでは明るくエネルギッシュなメンバーが全力でパフォーマンスする“清楚×シャカリキ”なギャップが武器です。<br /><br />3月から定期公演、5月には大阪MUSEにて半年ワンマンライブを行う予定です。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/anemoreel.mp4',
    x: 'anemoreel',
    insta: '@anemoreel_official',
    tiktok: '@anemoreel',
    other: '',
    withColle: 'LCckb63PnsUjP6IPWo0BfWGyzko1',
  },
  {
    name: 'Aproof【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Aproof.jpg',
      alt: 'Aproof',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '4gTqLJhE8VeSkl5SQeq1rAqflq62',
  },

  {
    name: '@youuuuu!!!【未提出】',
    yomi: 'あっとゆー',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/@youuuuu!!!.png',
      alt: '@youuuuu!!!',
    },
    content:
      '東京発！あっとゆー間にあなたを虜💘 4人組アイドルグループ！<br /><br />2025.09.22デビュー<br /><br />月乃星愛<br />樹波由依<br />薄明かりん<br />立花なの<br /><br /><br />実績<br />Summer jungle出演',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/youuuuu_info.mov',
    x: 'youuuuu_info',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'GLFG8mtUrvdwqChPfUXGBB0cg2I3',
  },
  {
    name: 'image',
    yomi: 'いまーじゅ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/image.jpeg',
      alt: 'image',
    },
    content:
      '2025年3月20日にデビューした名古屋発<br />5人組アイドルグループ「image」<br />コンセプト“emotional × パフォーマンス”。感情を揺さぶる表現力と、一体感あるステージを大切にライブをしています。<br />メンバーそれぞれの個性や魅力を発揮しながら、グループとしての完成度を追求し続けており、ビジュアル面・パフォーマンス面の両立を目指し日々努力を重ねています。<br /><br />実績 <br />2025 3月20日 伏見ライオンシアター 単独公演デビュー <br />2025 9月22日 大須X-HALL 1stワンマンライブ <br />2026 3月27日 名古屋Reny Limited 2nd ワンマンライブ<br /><br />メンバー<br />子守なの(ミントグリーン担当)<br />有栖れな(ピンク色担当)<br />生駒もも(黄色担当)<br />白雪りか(白色担当)<br />夜空しづき(赤色担当)',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/image__official.mov',
    x: 'image__official',
    insta: 'https://www.instagram.com/fleur_info?igsh=cmJjdG92NjNjYngx&utm_source=qr',
    tiktok: 'https://www.tiktok.com/@imageofficial.love?_r=1&_t=ZS-95Y9lWAIonR',
    other: '',
    withColle: 'sirgD1H5dbcrTgTbtYPrQHpKAec2',
  },
  {
    name: 'INOiZe↯【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/INOiZe↯.jpeg',
      alt: 'INOiZe↯',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'iROTORiDOLLY',
    yomi: 'いろとりどりー',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/iROTORiDOLLY.png',
      alt: 'iROTORiDOLLY',
    },
    content:
      '『あなたの毎日に彩りを』をコンセプトに活動している2025.11.22デビューのグループです。<br /><br />赤担当 藍羽のあ<br />ピンク担当 花野かほ<br />黄色担当 犬音うらら<br />水色担当 幸希なこ<br />オレンジ担当 川野笑菜<br />青担当 水城彩希<br />紫担当 橘ぜら<br />の7人組',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/iROTORiDOLLY_of.mp4',
    x: 'iROTORiDOLLY_of',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'TPerbnL7VjcP4zm4oTd21qbfEJH3',
  },
  {
    name: '「いつかのネバーランド」【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/「いつかのネバーランド」.jpg',
      alt: '「いつかのネバーランド」',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'IPrH2cL5L9QeLFQqa6qzq7r7Fxs2',
  },
  {
    name: 'オトメルキュール',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/オトメルキュール.jpeg',
      alt: 'オトメルキュール',
    },
    content:
      '2024年6月デビュー『かわいいだけじゃない！』をコンセプトに多彩な楽曲でステージパフォーマンスを重視した5人組の王道アイドルグループ。<br />グループ名は音＋乙女＋メルキュール（水星）3つの言葉を重ねた『オトメルキュール』',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/otomercure.mp4',
    x: 'otomercure',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'myfF2TxBLvRv7romQFNmDOPyZGu1',
  },
  {
    name: 'Otomeria【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Otomeria.png',
      alt: 'Otomeria',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'Coloration',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Coloration.jpeg',
      alt: 'Coloration',
    },
    content:
      '2025年2月27日デビュー、「心に溶け込む彩りに」をコンセプトに東京拠点で活動してる正統派王道アイドルグループです。<br /><br />Colorationメンバー<br />・有明つき  (ありあけつき)<br />メンバーカラー：オレンジ<br />出身地：三重県<br />・篠宮きき (しのみやきき)<br />メンバーカラー：イエロー<br />出身地：神奈川県<br />・花園もえ (はなぞのもえ)<br />メンバーカラー：ライトブルー<br />出身地：大阪府<br />・藤咲ゆら(ふじさきゆら)<br />メンバーカラー：パープル<br />出身地：静岡県',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/coloration_n.mp4',
    x: 'coloration_n',
    insta: 'https://www.instagram.com/coloration_n?igsh=MWVibjc2OTlpYnFsYw==',
    tiktok: 'https://www.tiktok.com/@coloration_n?_r=1&_t=ZS-9344H6D7UIa',
    youtube: 'https://youtube.com/@coloration_n?si=AxNk8P2y4NWBVEFM',
    other: '',
    withColle: 'oKupNxot4wVElherrsjribVDKo42',
  },
  {
    name: "colorin'c",
    yomi: 'カラリンク',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/colorin_c.png',
      alt: "colorin'c",
    },
    content:
      "<strong>-Profile-</strong><br />colorin'c (カラリンク)<br />大阪拠点3人組アイドルグループ<br />2026年2月19日東京にて始動。<br />4ヶ月連続シングルリリース中。<br />2026年08月18日大阪・梅田BANGBOOにてONEMAN LIVE開催。<br /><br /><strong>コンセプト</strong><br />真っ白なキャンバスに、<br />ひとつずつあなたと色を付けていく。<br /><br />出会うたびに広がっていく色の輪は、<br />やがて虹になる。<br /><br />“coloring（色付ける）”×“link（繋がる）”<br />あなたと出会い、心を繋ぐことで<br />初めて完成する“色”がある。<br /><br />「色で繋がり、未来を描く」<br /><br /><strong>MEMBER</strong><br />綾瀬りりあ<br />儚月れあ<br />三葉あゆな",
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/colorinc_info.m4v',
    x: 'colorinc_info',
    insta: 'https://www.instagram.com/colorinc_official/',
    tiktok: 'https://www.tiktok.com/@colorinc_official',
    other: '',
    withColle: '',
  },
  {
    name: 'ギミラブ！',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ギミラブ！.jpeg',
      alt: 'ギミラブ！',
    },
    content:
      '宮城県仙台市を拠点に活動する7人組の王道アイドルグループ。<br />2023年8月4日に結成され、切ないラブソングから日常をテーマにした楽曲、ホーム故郷を歌った曲など、グループとして、東北地方を中心にライブ活動を行っています。<br /><br />2025年の8月に新体制となり、2年間の大型プロジェクトを宣言し 、2027年8月に仙台PITでワンマンライブの開催が決定。<br />「あなたの日常に、小さな癒しと素敵な時間をお届けします」をコンセプトとして東北で唯一無二の王道アイドルグループを目指す。沢山の方にアイドル。ギミラブ！を知って欲しい！事からお祭りやイベントにも積極的に参加中！沢山の方の日常を全力で応援します！<br /><br />サブスクはもちろん、カラオケJOYSOUNDにも楽曲リリースあり！<br /><br /><br /><strong>メンバー紹介</strong><br />・齋藤　きらら（さいとう　きらら）<br />イエロー担当/宮城県出身/ダンス振り付け/うどん好き/<br />2005年4月18日<br /><a href="https://x.com/kirara_loveme" target="_blank" class="link">@kirara_loveme</a><br /><br />・姫咲　りい（ひめさく　りい）<br />レッド担当/いちごの国出身/ソロ曲あり/いちご好き<br /><a href="https://x.com/rii_loveme" target="_blank" class="link">@rii_loveme</a><br /><br />・葉月　みすず（はづき　みすず）<br />ピンク担当/宮城県出身/20歳/kpopダンス/最強ツインテール/みんなで守ってみすずたん♡<br /><a href="https://x.com/misuzu_loveme" target="_blank" class="link">@misuzu_loveme</a><br /><br />・夢野　未来（ゆめの　みらい）<br />パープル担当/宮城県出身/ビューティーお姉さん/ラジオ/和菓子好き/衣装制作/あいらぶ！ほやぼーや（気仙沼のゆるキャラ）<br /><a href="https://x.com/mirai_loveme" target="_blank" class="link">@mirai_loveme</a><br /><br />・成海　のん（なるみ　のん）<br />ブルー担当/北海道出身/アイドル1年生/中華好き/ヘアアレンジ,裁縫が得意！/多才ガール<br /><a href="https://x.com/non_loveme" target="_blank" class="link">@non_loveme</a><br /><br />・白宮　千愛（しろみや　ちあ）<br />ピュアホワイト担当/青森県出身,青森県在住/津軽弁/現役大学生/ギミラブ！候補生<br /><a href="https://x.com/chia_tongue" target="_blank" class="link">@chia_tongue</a><br /><br />・恋羽　おと（このは　おと）<br />ピュアグリーン担当/大阪府出身/宮城を沢山ひろめたい！/英検もってます！/ギミラブ！候補生<br /><a href="https://x.com/konoha_loveme" target="_blank" class="link">@konoha_loveme</a><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/givemelove_t.mov',
    x: 'givemelove_t',
    insta: 'https://www.instagram.com/givemelove_st?igsh=ang0eDZmOXR4bmpz&utm_source=qr',
    tiktok: 'https://vt.tiktok.com/ZSuGKqHYC/',
    other: 'https://pechunia-official.com/profile/',
    withColle: 'hDfXraawtqae8tuWXYED959wm0R2',
  },
  {
    name: 'キューハチパーセント！',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/キューハチパーセント！.jpg',
      alt: 'キューハチパーセント！',
    },
    content:
      '残り2%はあなたと作る！<br /><br />歌も、ダンスも、夢へも全力投球˖ . ݁𝜗𝜚. ݁₊<br /><br />『キューハチパーセント！』<br /><br /><br />2026年4月18日梅田amHALLにてデビュー！<br /><br />大阪を拠点に活動する7人組アイドルグループです！<br /><br /><br />ゆら <a href="https://x.com/yura_98percent" target="_blank" class="link">@yura_98percent</a><br /><br />♡誕生日：2007/01/22（19）<br /><br />♡ラブリーレッド🎀❤️<br /><br />♡出身地：大阪府<br /><br /><br />この <a href="https://x.com/kono_98percent" target="_blank" class="link">@kono_98percent</a><br /><br />♡誕生日：2010/08/02（15）<br /><br />♡メルティホワイト🧁🤍<br /><br />♡出身地：大阪府<br /><br /><br />ゆあ <a href="https://x.com/yua_98percent" target="_blank" class="link">@yua_98percent</a><br /><br />♡誕生日：2010/12/24（15）<br /><br />♡ぽかぽかオレンジ🔆🧡<br /><br />♡出身地：大阪府<br /><br /><br />にな <a href="https://x.com/nina_98percent" target="_blank" class="link">@nina_98percent</a><br /><br />♡誕生日：2009/2/7（17）<br /><br />♡マカロンピンク🎀🍨 <br /><br />♡出身地：徳島県<br /><br /><br />きょう <a href="https://x.com/kyou_98percent" target="_blank" class="link">@kyou_98percent</a><br /><br />♡誕生日：7/30<br /><br />♡メンバーカラー：ミルキーブルー🍼🩵<br /><br />♡出身地：宮城県<br /><br /><br />みのあ <a href="https://x.com/minoa_98percent" target="_blank" class="link">@minoa_98percent</a><br /><br />♡誕生日：11/2<br /><br />♡ハニーイエロー🍯💛<br /><br />♡出身地：大阪府<br /><br /><br />ありさ <a href="https://x.com/arisa_98percent" target="_blank" class="link">@arisa_98percent</a><br /><br />♡誕生日：2006/11/18（19）<br /><br />♡ミントグリーン🪽💚<br /><br />♡出身地：大阪府<br /><br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/98per_official.mov',
    x: '98per_official',
    insta: '',
    tiktok: '',
    other: 'https://www.youtube.com/@98percent.Official',
    withColle: 'gXy3zCbnF1WGwSaABNZlv5g399k1',
  },
  {
    name: '逆転ねこぱんちっ！【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/逆転ねこぱんちっ！.png',
      alt: '逆転ねこぱんちっ！',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'SANUGLOW',
    yomi: 'サンヌグロウ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/SANUGLOW.jpeg',
      alt: 'SANUGLOW',
    },
    content:
      'コンセプト『輝きを、繰り返す。』<br />活動開始は2024/11/29<br /><br />メンバー紹介<br />①紫色担当💜<br />紫雅楽ひとり(しがらきひとり)<br /><br />②白色担当🤍<br />他愛もある(たあいもある)<br /><br />③青色担当💙<br />王様ゆう(きんぐゆう)<br /><br />④水色担当🩵<br />琥翔なの(たいがなの)<br /><br /><br />2024年11月29日にFANJ twiceにてデビュー。<br />2026年3月15日には名古屋進出も視野に入れ、止まることなく展開を広げるSANUGLOW。<br />2025年11月29日の1周年ワンマンを経て、2026年4月15日には1.5周年ワンマンをOSAKA MUSEで開催し、会場を熱狂で埋め尽くしました。確かな勢いと存在感でファンを魅了しながら、さらなる高みへと歩みを進めています。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/SANUGLOW.mp4',
    x: 'SANUGLOW',
    insta: '@sanuglow_official',
    tiktok: '@sanuglow',
    other: '',
    withColle: '',
  },
  {
    name: 'Squall Line',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Squall Line.jpg',
      alt: 'Squall Line',
    },
    content:
      'きらめく雨粒は、やがて心を打つスコールへ。<br /><br />メンバー：柴山ゆち、東雲きゃん、神楽まつり、兎咲とうか、そして5月より月守ゆらを新メンバーに加え<br />更に勢いを増す、関西拠点の正統派アイドルユニットです。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/squallline_oa.mov',
    x: 'squallline_oa',
    insta: '',
    tiktok: '',
    other: 'https://lit.link/squallline_oa',
    withColle: 'vMNLhNZD3lPKu0Aqx8Ql5JKhDNh2',
  },
  {
    name: 'Chuu♡Cute',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Chuu♡Cute.jpg',
      alt: 'Chuu♡Cute',
    },
    content:
      'Chuu♡Cuteは、2025年7月11日にデビューした、まりちゅうこと長澤茉里奈プロデュースの6人組アイドルグループ。<br />リーダーでミントグリーン担当の橋本乃依は、俳優業に加えラジオパーソナリティーとしても活躍中。<br />サブリーダーでピンク担当の早川真由は、グラビアでも注目を集めている。<br />レッド担当の高橋遥花は、俳優活動に加え、テレビ埼玉「REDS TV GGR」にてアシスタントMCを務めるなど幅広く活動。<br />さらに2026年2月には、ベイビーブルー担当・吉田野乃、ホワイトラベンダー担当・大森あみ、イエロー担当・松本麗花が新たに加入。<br />6人体制となり、さらなる進化を遂げたChuu♡Cute。<br />それぞれの“かわいい”が重なり、一つの輝きを放つ彼女たちにぜひご注目ください。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/chuu_cute_.mov',
    x: 'chuu_cute_',
    insta: 'https://www.instagram.com/chuucute.official?igsh=MmdkbHd2cnN4Njg0&utm_source=qr',
    tiktok: '',
    other: 'https://chuu-cute.com',
    withColle: '',
  },
  {
    name: 'Twilight BlooM.',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Twilight BlooM..png',
      alt: 'Twilight BlooM.',
    },
    content:
      '<strong>コンセプト:</strong><br />可愛いって儚い♡<br /><br /><strong>活動開始日:</strong><br />2025/6/27<br /><br /><strong>メンバー紹介:</strong><br />赤色担当リーダー 茜つむ<br />ピンク担当 楚々萌愛<br />紫色担当 梓みり<br />ライトグリーン担当 瑞葉めろん<br />オレンジ色担当 日南すもも<br />水色担当 海愛りこな<br />黄色担当 望乃りり<br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/TWBL_official.mov',
    x: 'TWBL_official',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'WixrxoFPBRMKvIjx69jRCZk4DV33',
  },
  {
    name: 'tune time capsule【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/tune time capsule.png',
      alt: 'tune time capsule',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'にとくり。',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/にとくり。.png',
      alt: 'にとくり。',
    },
    content:
      '王道×清楚系をコンセプトに、爽やかで甘酸っぱい楽曲からキャッチーで盛り上がる楽曲まで幅広いパフォーマンスが見所です！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/Neatandclean727.mp4',
    x: 'Neatandclean727',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'lhNlLHC25Xheqfm1RATXkcrl0I33',
  },
  {
    name: 'New Crown【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/New Crown.png',
      alt: 'New Crown',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'Nody',
    yomi: 'のーでぃー',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Nody.jpg',
      alt: 'Nody',
    },
    content:
      'コンセプト:ハイパーメロウポップアイドル<br />活動期間:2024.5.30〜<br />実績:2025.5.29 1周年単独公演梅田クアトロ実施<br />来月5/29に単独公演心斎橋BIGCAT公演開催',
    x: 'no_day_official',
    insta: '',
    tiktok: 'https://www.tiktok.com/@no_dy_official?_r=1&_t=ZS-95gsFBtdQCi',
    other: 'https://lit.link/nodayofficial2024',
    withColle: 'cuBgyymEpgbfSHqIW7ALcxMaq9X2',
  },
  {
    name: 'NEOTOKYO-TRIBE【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/NEOTOKYO-TRIBE.jpeg',
      alt: 'NEOTOKYO-TRIBE',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'Harley Queen',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Harley Queen.jpg',
      alt: 'Harley Queen',
    },
    content:
      '2021年4月29日に結成し、2023年12月30日の活動休止を経て、<br />2025年9月13日に事務所移転も伴い、新たな気持ちで活動開始しました。<br />HarleyQueenはステージと客席が一体となって盛り上がることのできるライブパフォーマンスが最大の魅力です。<br />是非、ライブで声を出したり、一緒に踊ったりしてください！<br />暑い夏に熱いパフォーマンスを届けたいので応援よろしくお願い致します！<br /><br />メンバー<br />北川らん<br />担当カラー：青色<br />Xアカウント：@Harley_Ran<br /><br />水城かぐや<br />担当カラー：赤色<br />Xアカウント：@harley_kaguya<br /><br />卯月えり<br />担当カラー：白色<br />Xアカウント：@Harley_eri_',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/Harley_Queen_3.mp4',
    x: 'Harley_Queen_3',
    insta: '',
    tiktok: '',
    other: 'https://timetreeapp.com/public_calendars/harleyqueen',
    withColle: 'c81Q8OxL7ZeClaKwGWgNvHSIhnY2',
  },
  {
    name: 'HIGH SPY DOLL',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/HIGH SPY DOLL.png',
      alt: 'HIGH SPY DOLL',
    },
    content:
      'HIGH＝高い、ハイクオリティーな<br />S（STYLE）→独自のとらわれないスタイル、表現<br />P（PERFORMANCE）→音楽、演技、ダンス、エンタメ<br />Y（YOUTH）→いつまでも忘れない子供心やまっすぐな思い<br />＝SPY→時に応じて”七変化、何者にでもなれる<br />私たちが欲しいのはみんなの笑顔、感動、勇気、元気、などそんな幸せを感じてもらえる瞬間！<br /><br /><br />アイドルの固定概念を180度変える<br />彼女達のメッセージ性高く熱いステージ、<br />言語の壁なんか飛び越え様々なエンタメで<br />国境を越えて愛される最強のエンタメ集団に！<br /><br /><br /><strong>2024年</strong><br />・1stアルバムリリース<br />・レコ発東名阪福ツアー<br />・＠JAM EXPO出演<br /><br /><strong>2025年</strong><br />・ベビタピメンバー加入<br />・ベビタピフェスin国立代々木競技場第二体育館 出演<br />・小学館〝ちゃお〟掲載<br />・大阪万博ステージ 出演<br /><br />2026.9.9 BIGCATワンマン開催！<br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/tenseishitaspd.mov',
    x: 'https://x.com/tenseishitaspd',
    insta: '',
    tiktok: 'https://www.tiktok.com/@spadochan0613?_r=1&_t=ZS-95fhKdGtoDy',
    other: '',
    withColle: '',
  },
  {
    name: 'ひとつキラリ',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ひとつキラリ.jpeg',
      alt: 'ひとつキラリ',
    },
    content:
      'キラリと光る、たった一つの誇りになりたい。<br />あなたのために、WONDER CUTENESS OVERLOAD!!【奇跡の可愛さがすぎる】<br /><br />活動開始日<br />2025年2月24日<br /><br />メンバー紹介<br />如月蓮華　【赤】 グループ唯一の金髪ぎゃる<br />七宮夜々　【黄色】天真爛漫わがままムードメーカー<br />時禾ろり　【ピンク】 <br />キラリの煽り担当甘えん坊わんちゃん<br />月下恋　【水色】 踊れるほんわかよちよちペンギン<br />リア　【白】 韓国から来たあざといお姫ちゃま<br />爽音ひなた　【青】キラリの朝の顔、爽やかダンサー！<br /><br />実績<br />2025年 関ケ原唄姫合戦 予戦会突破・出場',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/hitotsukirari.mp4',
    x: 'hitotsukirari',
    insta: '',
    tiktok: '',
    other: 'https://youtube.com/channel/UCny3YZG9GYJmIfQaalQKUdQ?si=L8ZWXwSLIff5sKvS',
    withColle: '3HqK7glCVsR7HUNXdNwfLcHjzNc2',
  },
  {
    name: 'ヒップバーン【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ヒップバーン.jpg',
      alt: 'ヒップバーン',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'R2JdPyP1jnO2zHi3lvH1RhPrAAk1',
  },
  {
    name: '秘密結社フローリス【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/秘密結社フローリス.jpg',
      alt: '秘密結社フローリス',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'FIRST DREAM',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/FIRST DREAM.jpg',
      alt: 'FIRST DREAM',
    },
    content:
      '”私とあなたの夢を叶えにいく 初めて描いたあの日の想いを抱いて”<br /><br />「青春」と「夢」を描く楽曲派アイドルグループ<br /><br />佐藤湖々音、桜井明花、北山瑞姫、綾瀬かりんの４人で夢を叶える旅路を歩む<br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/firstdream_bte.mov',
    x: 'firstdream_bte',
    insta:
      'https://www.instagram.com/firstdream_official_?igsh=MTM3MnRsMnJ2MHZ2bQ%3D%3D&utm_source=qr',
    tiktok: 'https://www.tiktok.com/@firstdream_official_?_r=1&_t=ZS-95gfwjhSwzo',
    other: 'https://lit.link/firstdream',
    withColle: '',
  },
  {
    name: 'BrainBeat',
    yomi: 'ぶれいんびーと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/BrainBeat.jpg',
      alt: 'BrainBeat',
    },
    content:
      'BrainBeatは、\“ピュア×ギャル\”というアンビバレントな魅力を武器に、「どんな困難にも抗い、何度でもステージへ、何度でも前へ」を掲げて活動するアイドルグループです。<br />2025年1月31日に始動。現在は、ぽれあ・ひな・さやの3名を中心に活動しております。ユーロビートや重低音を軸とした高揚感ある楽曲と、熱量でフロアを巻き込むライブを強みとして、一つひとつのステージを積み重ねてまいりました。<br /> <br/>決して平坦ではない道のりの中でも立ち止まらず、自分たちの“好き”と覚悟で前に進み続けていることが、今のBrainBeatの一番の核です。<br />そして関ケ原唄姫合戦は、グループ結成時から思い描いてきた夢の舞台の一つでもあります。<br /><br />この予戦会もただの挑戦ではなく、本気で夏へつなげるための勝負の場だと思っております。<br/>一度見たら忘れられない熱量で「このグループを本戦で見たい」と思っていただけるライブをお届けいたします！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/brainbeat_idol.mp4',
    x: 'brainbeat_idol',
    insta: '',
    tiktok: 'https://www.tiktok.com/@brainbeat_',
    other: 'https://maux.jp/artist.html',
    withColle: 'bJHUwVCBUGYh7r4no9TgMCv5b913',
  },
  {
    name: 'BLUE REGRET。【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/BLUE REGRET。.png',
      alt: 'BLUE REGRET。',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'POPING CANDY.',
    yomi: 'ぽぴんぐきゃんでぃ',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/POPING CANDY..jpeg',
      alt: 'POPING CANDY.',
    },
    content:
      'コンセプト<br /><strong>POPING CANDY.（ぽぴんぐきゃんでぃ）</strong>は、<br />“あまくて はじける”をコンセプトに活動する3人組キャンディ系アイドルグループ🍬✨<br /><br />ライブも、日常も、ときめきに変えていく——<br /><br /><strong>「君と一緒に弾け飛ぶ！」</strong>を合言葉に、<br /><br />見た人の心を甘くPOPに彩ります💫<br /><br /><br />活動開始日<br /><br />プレデビュー : 2024/12/1<br /><br />デビュー : 2025/10/5<br /><br />メンバー紹介<br /><br />・黒沢凪　ブルーハワイキャンディ担当<br />・来餅いの　レモネードキャンディ担当<br />・藤咲める　グレープヨーグルトキャンディ担当',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/POPINGCANDY_gf.mov',
    x: 'POPINGCANDY_gf',
    insta: '',
    tiktok: 'https://www.tiktok.com/@popingcandy_gf',
    other: 'https://popingcandygf.wixsite.com/popingcandy',
    withColle: 'cjl4ogbTBaR1l3zFJ7eB7wLJHOl1',
  },
  {
    name: 'vVibe!',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/vVibe!.jpg',
      alt: 'vVibe!',
    },
    content:
      '2024年7月結成、可愛いだけでは終わらない“高ヴァイブス型”5人組アイドル・vVibe!。<br /><br />王道アイドルらしい華やかさを持ちながら、対バンで空気を塗り替えるライブ力と、楽曲ごとに表情を変える幅広い世界観を武器に活動中。<br /><br />メンバーそれぞれの個性が立った楽曲とステージ、思わず巻き込まれるコール・mixの一体感、そして初見でも熱くなれるライブがvVibe!の魅力です。<br /><br />関ヶ原唄姫合戦2026予戦会では、この熱をもっと大きな景色へ繋げるために本気で挑戦します。ぜひvVibe!を知ってください。<br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/vvibemuse.mov',
    x: 'vvibemuse',
    insta: '',
    tiktok: 'https://www.tiktok.com/@vvibe007',
    other: '',
    withColle: '',
  },
  {
    name: 'プラチナリボン【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/プラチナリボン.jpeg',
      alt: 'プラチナリボン',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'BabyDolls【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/BabyDolls.png',
      alt: 'BabyDolls',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'Mihiro【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Mihiro.jpeg',
      alt: 'Mihiro',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'MiDi ON!【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/MiDi ON!.jpeg',
      alt: 'MiDi ON!',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'r7rL4X1hw7edtEl57uPShhlqEz22',
  },
  {
    name: 'Maycry Liz【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Maycry Liz.jpeg',
      alt: 'Maycry Liz',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'melnoir',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/melnoir.jpeg',
      alt: 'melnoir',
    },
    content:
      '『あなたの孤独や不安を溶かし虜にする』をコンセプトに活動している2026.2.19デビューの5人組アイドルグループ<br /><br />赤担当 愛河せいら<br />ピンク担当 恋猫える<br />水色担当 乙月あかり<br />オレンジ担当 陽咲あゆら<br />紫担当 かなみとま',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/melnoir_.mov',
    x: 'melnoir_',
    insta: '',
    tiktok: '@melnoir_info',
    other: '',
    withColle: '8DgaS17zV0T54QOU3W3ee1CgJin2',
  },
  {
    name: 'めろでぃらびっと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/めろでぃらびっと.png',
      alt: 'めろでぃらびっと',
    },
    content:
      '2026年4月19日にデビューした、元LOVE9LOVE「おうかなつ」プロデュースの関西エリアで活動しているアイドルグループになります。<br />アイドルオタクアイドルとして活動していた「おうかなつ」の経験を基に集まった全員前世無し未経験者で揃った可愛らしい王道系７人組のグループです。<br />関西人らしい明るいキャラで可愛さをお届け出来るように頑張ります。',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/melorabbi.mov',
    x: 'melorabbi',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '9A7aBJBrMuZs2O1HofmGrOnKe6i2',
  },
  {
    name: '寄絃 - Yo2La',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Yo2La.jpg',
      alt: 'Yo2La',
    },
    content:
      '2026年4月28日デビュー<br />after all プロデュース 7人組アイドルグループ<br /><br /><br /><strong>◼ メンバー</strong><br />◇御影 なぎ メンバーカラー：赤色 属性：炎<br />X：<a href="https://twitter.com/nagi_Yo2La" target="_blank" class="link">@nagi_Yo2La</a><br /><br />◇瀬織津 あい メンバーカラー：青色 属性：水<br />X：<a href="https://twitter.com/ai_Yo2La" target="_blank" class="link">@ai_Yo2La</a><br /><br />◇明日羽 ゆゆ メンバーカラー：黄色 属性：星<br />X：<a href="https://twitter.com/yuyu_Yo2La" target="_blank" class="link">@yuyu_Yo2La</a><br /><br />◇結良姫 かのん メンバーカラー：白色 属性：光<br />X：<a href="https://twitter.com/kanon_Yo2La" target="_blank" class="link">@kanon_Yo2La</a><br /><br />◇咲夜 めぐ メンバーカラー：紫色 属性：幻<br />X：<a href="https://twitter.com/megu_Yo2La" target="_blank" class="link">@megu_Yo2La</a><br /><br />◇月詠 てん メンバーカラー：緑色 属性：風<br />X：<a href="https://twitter.com/ten_Yo2La" target="_blank" class="link">@ten_Yo2La</a><br /><br />◇津羅凪 アヤ メンバーカラー：ピンク色 属性：愛<br />X：<a href="https://twitter.com/aya_Yo2La" target="_blank" class="link">@aya_Yo2La</a><br /><br /><br /><strong>◼︎ プロデューサー</strong><br />after all<br />愛知県一宮市出身<br />レフティギタリスト・ベーシスト<br /><br />数多くのアイドル楽曲を手掛ける音楽プロデューサー。<br />作詞・作曲・編曲・レコーディングまでを一貫して手掛け、<br />トータルでのサウンドプロデュースを得意としている。<br /><br />',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/Yo2La_official.mp4',
    x: 'Yo2La_official',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'MQK23hLDApMZVrrXJz7J9gdAR5A3',
  },
  {
    name: '夕凪のスピカ【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/夕凪のスピカ.jpg',
      alt: '夕凪のスピカ',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'zbWm77blsFRhG1Y58XrwgAKaon12',
  },
  {
    name: 'ゆにきゅーと',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ゆにきゅーと.png',
      alt: 'ゆにきゅーと',
    },
    content: '可愛い唯一の存在。エネルギッシュのあるライブで皆さんを楽しませます！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/unicute131.mov',
    x: 'unicute131',
    insta: '',
    tiktok: '',
    other: '',
    withColle: 'vmBMMyHrrPMjpGsIr3ES88n7rK62',
  },
  {
    name: 'ラビットビット',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/ラビットビット.jpg',
      alt: 'ラビットビット',
    },
    content:
      'コールボードを持ったパフォーマンスを行います！<br />オタ芸・デコトラ運転手・ひき肉料理の使い手・保育士・心霊スポットの住人の5人組で活動しております！<br /><br />今年も暑い夏をさらに熱くしていきます！！',
    movie: '',
    x: 'rabbitbit2022',
    insta: 'https://www.instagram.com/rabbitbit2022/',
    tiktok: 'https://www.tiktok.com/@usa_chans',
    other: '',
    withColle: 'CpYfCHdzayWXTkJUR1wfs49Qcpu1',
  },
  {
    name: 'Lumi Prima【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Lumi Prima.jpg',
      alt: 'Lumi Prima',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'LEVEL7【未提出】',
    yomi: '',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/LEVEL7.jpg',
      alt: 'LEVEL7',
    },
    content: '',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/.mov',
    x: '',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '',
  },
  {
    name: 'Re:M!ND',
    yomi: 'りまいんど',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/Re_M!ND.png',
      alt: 'Re:M!ND',
    },
    content:
      '『あなたの記憶に残る』をコンセプトに活動している2025.11.22デビューのグループです。<br /><br />赤担当 蘭カレン<br />ピンク担当 花宮美玲<br />オレンジ担当 彩木春華<br />水色担当 科乃あお<br />紫担当 音瀬夢香<br />白担当　春日野珠理<br />の6人組',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/ReMIND_info.mp4',
    x: 'ReMIND_info',
    insta: '',
    tiktok: '',
    other: '',
    withColle: '2flKNcg7KzPu5ME1WxlaCI9TRls1',
  },
  {
    name: 'わんみゅーず！',
    img: {
      src: 'https://sekigahara-idolwars.net/2026/yosen/artists/わんみゅーず！.png',
      alt: 'わんみゅーず！',
    },
    content:
      '2025年12月12日デビュー！<br />大阪拠点 テーマパークコンセプトのわんみゅーず！です！<br />メロディレッド担当 甘苺るう (あまいるう)<br />ときめきぴんく担当 兎月みあい (うづきみあい)<br />レモネードイエロー担当 日奈こゆ (ひなこゆ)<br />わがままぱーぷる担当 天和あもね (てんのあもね)<br />わたあめらいとぶるー担当 空音りのん (そらねりのん)<br />3月16日に追加メンバーとなった<br />おこじょほわいと担当 柊羽夏 (ひいらぎはな)<br /><br />からなる6人組アイドルグループ！<br />アー写のデザイン制作から加工編集、衣装デザイン、イベントフライヤー、チェキ券やグッズイラストやデザイン、曲の作詞等 18歳の甘苺るうが全て制作しプロデュースしています。<br /><br />歌担当やダンス担当、可愛い担当や美人で推したいお笑い(？！)担当、人類の垣根を越える奇想天外担当など<br />1人残らず個性が強すぎる仲良しグループ！<br />個人の個性に限らず楽曲もいろんなジャンルが楽しめます！<br /><br />テレビ大阪主催「はばたけアイドルフェス」シリーズにも出演<br /><br />今回初めての大きな舞台への挑戦です！',
    movie: 'https://lime-light.tv/images/2026/yosen/artists/movie/onemuseofficial.mp4',
    x: 'onemuseofficial',
    insta: '@onemuse_official',
    tiktok: '@onemuseofficial',
    other: 'https://lit.link/onemuse',
    withColle: '5UhLVOX0SBemqfarxRZ1mujGNd13',
  },
]
