import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const edoEvents: YosenAccordionProps[] = [
  {
    cName: 'edo',
    title: '其の一',
    date: '2025年5月9日（金）',
    open: '18:30',
    start: '19:00',
    place: 'シアターマーキュリー新宿',
    artists: 'Party chuuuN!／カリスマめんざいふっ！／ビーバイユー',
    ticket: 'https://tiget.net/events/399674',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_11.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の二',
    date: '2025年5月11日（日）',
    open: '12:00',
    start: '12:30',
    place: 'シアターマーキュリー新宿',
    artists: 'Party chuuuN!／青春のフロンティア／アクアリウム。／カリスマめんざいふっ！',
    ticket: 'https://tiget.net/events/400182',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_21.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の三',
    date: '2025年5月11日（日）',
    open: '16:00',
    start: '16:30',
    place: 'シアターマーキュリー新宿',
    artists: 'ビーバイユー／青春のフロンティア／アクアリウム。',
    ticket: 'https://tiget.net/events/400185',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_31.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の四',
    date: '2025年5月13日（火）',
    open: '17:30',
    start: '18:00',
    place: 'TwinBoxAKIHABARA/GARAGE',
    artists:
      "Party chuuuN!／カリスマめんざいふっ！／ビーバイユー／ルシフェルの園。／STELLASTELLA／Poppin' Parade",
    ticket: 'https://tiget.net/events/400422',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_41.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の五',
    date: '2025年5月14日（水）',
    open: '17:00',
    start: '17:30',
    place: '浅草花劇場',
    artists:
      'カリスマめんざいふっ！／ja惹句ck／ラビットビット／チキータ／アクアリウム。／ノルニル／ハレとハレ！＜ゲスト＞ DREAMING MONSTER／ワンダーウィード 天',
    ticket: 'https://tiget.net/events/400781',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_51.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の六',
    date: '2025年5月15日（木）',
    open: '17:00',
    start: '17:30',
    place: 'TwinBoxAKIHABARA/GARAGE',
    artists:
      "ビーバイユー／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／縷々／ひとつキラリ／アクアリウム。／STELLASTELLA／parfait d'ange／ハレとハレ！／プエラの絶対値＜ゲスト＞ SPRISE",
    ticket: 'https://tiget.net/events/400834',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_61.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の七',
    date: '2025年5月16日（金）',
    open: '17:45',
    start: '18:15',
    place: 'シアターマーキュリー新宿',
    artists: "Party chuuuN!／ja惹句ck／Poppin' Parade／IDOLEST／プエラの絶対値／＜ゲスト＞ SPRISE",
    ticket: 'https://tiget.net/events/400878',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_71.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の八',
    date: '2025年5月18日（日）',
    open: '11:30',
    start: '12:00',
    place: 'シアターマーキュリー新宿',
    artists: 'Party chuuuN!／ja惹句ck／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／縷々／ひとつキラリ',
    ticket: 'https://tiget.net/events/401682',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_81.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の九',
    date: '2025年5月18日（日）',
    open: '16:30',
    start: '17:00',
    place: 'シアターマーキュリー新宿',
    artists: 'Party chuuuN!／ja惹句ck／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／縷々／ひとつキラリ',
    ticket: 'https://tiget.net/events/400878',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_91.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十',
    date: '2025年5月19日（月）',
    open: '16:30',
    start: '17:00',
    place: '渋谷ストリームホール',
    artists:
      "Party chuuuN!／ja惹句ck／Poppin' Parade／アクアリウム。／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／縷々／ひとつキラリ／プエラの絶対値＜ゲスト＞花いろは／なみだ色の消しごむ",
    ticket: 'https://tiget.net/events/402094',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_101.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十一',
    date: '2025年5月20日（火）',
    open: '16:15',
    start: '16:45',
    place: 'TwinBoxAKIHABARA/GARAGE',
    artists:
      "カリスマめんざいふっ！／ビーバイユー／ja惹句ck／ルシフェルの園。／チキータ／アクアリウム。／奏音コレクト／ノルニル／Poppin' Parade／STELLASTELLA／ハレとハレ！／ラビットビット",
    ticket: 'https://tiget.net/events/402258',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_111.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十二',
    date: '2025年5月21日（水）',
    open: '16:30',
    start: '17:00',
    place: 'シアターマーキュリー新宿',
    artists:
      "ビーバイユー／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／縷々／ひとつキラリ／ルシフェルの園。／チキータ／IDOLEST／parfait d'ange／ハレとハレ！／Party chuuuN!",
    ticket: 'https://tiget.net/events/402333',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_121.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十三',
    date: '2025年5月22日（木）',
    open: '17:00',
    start: '17:30',
    place: 'shibuya GRIT',
    artists:
      "Party chuuuN!／ビーバイユー／ja惹句ck／Poppin' Parade／STELLASTELLA／奏音コレクト／IDOLEST／parfait d'ange／ハレとハレ！／ラビットビット",
    ticket: 'https://tiget.net/events/402334',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_131.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十四',
    date: '2025年5月24日（土）',
    open: '11:30',
    start: '12:00',
    place: 'シアターマーキュリー新宿',
    artists:
      "Poppin' Parade／青春のフロンティア／ラビットビット／ルシフェルの園。／ノルニル／IDOLEST／縷々／ハレとハレ！",
    ticket: 'https://tiget.net/events/403159',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_141.JPG',
    image2: '',
  },
  {
    cName: 'edo',
    title: '其の十五',
    date: '2025年5月24日（土）',
    open: '16:30',
    start: '17:00',
    place: 'シアターマーキュリー新宿',
    artists:
      "カリスマめんざいふっ！／ja惹句ck／青春のフロンティア／ラビットビット／STELLASTELLA／≪√PlusF✯rt≫~ﾙｰﾄﾌﾟﾘｭﾌｫｰﾙ~／ひとつキラリ／Poppin' Parade／parfait d'ange／Party chuuuN!／縷々",
    ticket: 'https://tiget.net/events/403170',
    image1: 'https://yosen2025.sekigahara-idolwars.net/picture/edo/edo_151.JPG',
    image2: '',
  },
]
