import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const osakaEvents: YosenAccordionProps[] = [
  {
    cName: 'osaka',
    title: '其の一',
    date: '2025年5月10日(土)',
    open: '11:30',
    start: '12:00',
    place: '京橋Arc',
    artists: 'LOTUS MARRY／むげんこんぜ／Qu♡Aly／ぷりしえーる／ゼロキョリハーツ',
    ticket: 'https://tiget.net/events/399890',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_11.JPG',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の二',
    date: '2025年5月10日(土)',
    open: '16:30',
    start: '17:00',
    place: '京橋Arc',
    artists:
      'LOTUS MARRY／むげんこんぜ／ふぁんたす！／ぷりしえーる／ゼロキョリハーツ／あおぞらをキミに／Qu♡Aly',
    ticket: 'https://tiget.net/events/399893',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_21.JPG',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の三',
    date: '2025年5月17日(土)',
    open: '12:30',
    start: '13:00',
    place: '京橋Arc',
    artists: 'ゼロキョリハーツ／Qu♡Aly／ふぁんたす！',
    ticket: 'https://tiget.net/events/401449',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_31.png',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の四',
    date: '2025年5月17日(土)',
    open: '18:00',
    start: '18:30',
    place: '京橋Arc',
    artists: 'ゼロキョリハーツ／Qu♡Aly／ふぁんたす！＜ゲスト＞NEO BREAK',
    ticket: 'https://tiget.net/events/401451',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_41.png',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の五',
    date: '2025年5月18日(日)',
    open: '12:30',
    start: '13:00',
    place: '京橋Arc',
    artists: 'アクアリウム。／ゼロキョリハーツ／あおぞらをキミ',
    ticket: 'https://tiget.net/events/402070',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_51.JPG',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の六',
    date: '2025年5月18日(日)',
    open: '17:45',
    start: '18:15',
    place: '京橋Arc',
    artists: 'むげんこんぜ／Qu♡Aly／ふぁんたす！／ゼロキョリハーツ＜ゲスト＞NEO BREAK',
    ticket: 'https://tiget.net/events/402072',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_61.JPG',
    image2: '',
  },
  {
    cName: 'osaka',
    title: '其の七',
    date: '2025年5月23日(金)',
    open: '18:30',
    start: '19:00',
    place: '京橋Arc',
    artists: 'LOTUS MARRY／ゼロキョリハーツ／Qu♡Aly／ぷりしえーる',
    ticket: 'https://tiget.net/events/402904',
    image1: 'https://yosen2025.lime-light.tv/picture/osaka/osaka_71.JPG',
    image2: '',
  },
]
