import { YosenAccordionProps } from '@/templates/accordion/YosenAccordion'

export const owariEvents: YosenAccordionProps[] = [
  {
    cName: 'owari',
    title: '其の一',
    date: '2025年5月9日（金）',
    open: '18:00',
    start: '18:30',
    place: '名古屋ReNY limited',
    artists: 'なないろ∞ミルキーウェイ／Lollipop♡CHU／Y∀KiN／アクアリウム。',
    ticket: 'https://tiget.net/events/399677',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_11.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の二',
    date: '2025年5月10日（土）',
    open: '12:00',
    start: '12:30',
    place: '名古屋DEEP',
    artists: 'なないろ∞ミルキーウェイ／Lollipop♡CHU／いざ参らん／恋セ界-koiseka-／アクアリウム。',
    ticket: 'https://tiget.net/events/399882',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_21.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の三',
    date: '2025年5月10日（土）',
    open: '17:00',
    start: '17:30',
    place: '名古屋DEEP',
    artists: 'なないろ∞ミルキーウェイ／Lollipop♡CHU／恋セ界-koiseka-／アクアリウム。',
    ticket: 'https://tiget.net/events/399885',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_31.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の四',
    date: '2025年5月16日（金）',
    open: '17:30',
    start: '18:00',
    place: 'Lives NAGOYA',
    artists:
      "なないろ∞ミルキーウェイ／Lollipop♡CHU／カリスマめんざいふっ！／いざ参らん／LOTUS MARRY／parfait d'ange＜ゲスト＞ Sweet Alley",
    ticket: 'https://tiget.net/events/401102',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_41.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の五',
    date: '2025年5月17日（土）',
    open: '10:30',
    start: '11:00',
    place: '名古屋DEEP',
    artists: 'カリスマめんざいふっ！／LOTUS MARRY／恋セ界-koiseka-',
    ticket: 'https://tiget.net/events/401384',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_51.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の六',
    date: '2025年5月17日（土）',
    open: '14:30',
    start: '15:00',
    place: '名古屋DEEP',
    artists: 'Y∀KiN／ぷりしえーる／恋セ界-koiseka-',
    ticket: 'https://tiget.net/events/401385',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_61.png',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の七',
    date: '2025年5月18日（日）',
    open: '11:00',
    start: '11:30',
    place: '名古屋ライオンリミテッド',
    artists: 'カリスマめんざいふっ！／LOTUS MARRY／恋セ界-koiseka-／Y∀KiN／なないろ∞ミルキーウェイ',
    ticket: 'https://tiget.net/events/402068',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_71.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の八',
    date: '2025年5月18日（日）',
    open: '16:30',
    start: '17:00',
    place: '名古屋ライオンリミテッド',
    artists: 'なないろ∞ミルキーウェイ／Lollipop♡CHU／Y∀KiN／恋セ界-koiseka-',
    ticket: 'https://tiget.net/events/402069',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_81.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の九',
    date: '2025年5月23日（金）',
    open: '18:00',
    start: '18:30',
    place: '名古屋DIVA',
    artists: "なないろ∞ミルキーウェイ／Lollipop♡CHU／いざ参らん／parfait d'ange／Y∀KiN",
    ticket: 'https://tiget.net/events/402879',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_91.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の十',
    date: '2025年5月24日（土）',
    open: '12:00',
    start: '12:30',
    place: '名古屋DEEP',
    artists:
      'なないろ∞ミルキーウェイ／Lollipop♡CHU／いざ参らん／​​Y∀KiN／LOTUS MARRY／恋セ界-koiseka-',
    ticket: 'https://tiget.net/events/403194',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_101.JPG',
    image2: '',
  },
  {
    cName: 'owari',
    title: '其の十一',
    date: '2025年5月4日（土）',
    open: '17:30',
    start: '18:00',
    place: '名古屋DEEP',
    artists:
      'なないろ∞ミルキーウェイ／Lollipop♡CHU／いざ参らん／​​Y∀KiN／LOTUS MARRY／恋セ界-koiseka-',
    ticket: 'https://tiget.net/events/403196',
    image1: 'https://yosen2025.lime-light.tv/picture/owari/owari_111.JPG',
    image2: '',
  },
]
