import { LegacyNewsType } from '@/domain/news'

export const news2025: LegacyNewsType[] = [
  {
    id: 24,
    date: '2025.07.18',
    title: '注意事項',
    context: ['', '⚔️関ケ原唄姫合戦を楽しむ為に皆様お守りください⚔️', '', '', '', ''],
    urls: ['https://tiget.net/events/407817'],
    img: [
      'https://pbs.twimg.com/media/GwD6WgaWQAACxiv?format=jpg&name=4096x4096',
      'https://pbs.twimg.com/media/GwD6WgYacAA7HSH?format=jpg&name=4096x4096',
    ],
  },
  {
    id: 23,
    date: '2025.07.17',
    title: 'シャトルバス情報🚍',
    context: [
      '',
      '🌟**シャトルバス運行します！**🌟',
      '',
      '📍運行ルート：',
      '・JR関ケ原駅 ⇆ 桃配運動公園',
      '・メナード臨時駐車場 ⇆ 桃配運動公園',
      '',
      '',
      '💴料金：片道600円',
      '※電子決済は PayPay のみ対応しております。',
      '',
      '',
      '⚠️ご注意：',
      '天候や道路状況により、発着時間に遅れが生じる場合がございます。予めご了承ください。',
      '',
      '',
      '',
    ],
    urls: ['https://tiget.net/events/407817'],
    img: ['https://pbs.twimg.com/media/GwDObbjXAAAtuqi?format=jpg&name=4096x4096'],
  },
  {
    id: 22,
    date: '2025.07.15',
    title: 'エリアマップ発表!!',
    context: [
      '',
      'ライブエリアで熱狂するもよし、',
      'フードエリアで夏の味に舌鼓を打つもよし、',
      '木陰で風に吹かれながらひと休みするもよし。',
      '',
      '',
      '楽しみ方は自由——この夏の主役は、キミだ。',
      'さあ、全力で関ケ原を遊び尽くそう！',
      '',
      '',
      '',
    ],
    urls: ['https://tiget.net/events/407817'],
    img: ['https://pbs.twimg.com/media/Gv5WCrWa4AALTB8?format=jpg&name=4096x4096'],
  },
  {
    id: 21,
    date: '2025.07.15',
    title: '物販タイムテーブル発表!!',
    context: ['', '物販タイムテーブル発表!!', ''],
    urls: ['https://tiget.net/events/407817'],
    img: ['https://pbs.twimg.com/media/Gv4XN2za4AIosUS?format=jpg&name=4096x4096'],
  },
  {
    id: 20,
    date: '2025.07.11',
    title: '駐車場情報 🚗💨',
    context: [
      '',
      '',
      '🅿️第一駐車場（会場隣接）',
      '--------------------------',
      'ご利用には駐車券の購入が必須です🎫',
      '',
      '',
      '🅿️ 第二駐車場（臨時駐車場）',
      '--------------------------',
      '📍関ヶ原メナードランド跡地 臨時駐車場',
      '〒503‑1545 岐阜県不破郡関ケ原町大字玉1407',
      '✅ 無料でご利用いただけます',
      '',
      '',
      '🚌 シャトルバス運行します',
      '--------------------------',
      '関ケ原駅 付近／第二駐車場（関ヶ原メナードランド跡地）から',
      '会場までシャトルバス（有料）を運行いたします！',
      '※運行時間等は、少々お待ちください！',
      '',
      'ぜひご利用ください✨',
    ],
    urls: ['https://tiget.net/events/414947'],
    img: ['https://pbs.twimg.com/media/GvkIS17WQAEpw6U?format=jpg&name=4096x4096'],
  },
  {
    id: 19,
    date: '2025.07.09',
    title: 'ニコニコ生放送にて配信決定 ',
    context: [
      '',
      '',
      "📺この夏、画面越しでも'関ケ原'へ。",
      'ニコニコ生放送にて、3日間の熱戦を生中継(徳川ステージのみ)‼️',
      '',
      '遠くにいても、会場にいなくても',
      'この夏、あの場所の熱と音と涙を、',
      'リアルタイムで体感してください🔥🌈',
      '',
      '',
    ],
    urls: [''],
    img: ['https://pbs.twimg.com/media/GvZmLIlWQAA2xbB?format=jpg&name=4096x4096'],
  },
  {
    id: 18,
    date: '2025.07.07',
    title: '📢 公式Instagramを開設しました📢',
    context: [
      '',
      '',
      '今年の関ケ原がもっと楽しみになるような',
      '最新情報や舞台裏、出演者の様子などを',
      'たくさん発信していきます🌈✨',
      '',
      '',
      'ぜひチェックしてね🫶💗',
      '',
      '',
    ],
    urls: ['https://instagram.com/_idolwars'],
    img: [
      'https://pbs.twimg.com/media/GvQVaFGacAAImc-?format=jpg&name=4096x4096',
      'https://pbs.twimg.com/media/GvQVfvFW8AAImhY?format=jpg&name=4096x4096',
    ],
  },
  {
    id: 17,
    date: '2025.07.07',
    title: 'ロードモバイル布陣／タイムテーブル更新!!',
    context: [
      '',
      '',
      '⚔️ロードモバイル布陣として4組 出陣決定⚔️',
      '',
      '',
      'はいどーも！テラスマです！（20,21）',
      '世界逆転宣言！（20,21）',
      'ぺりきゅらむ(21)',
      'ちあもあ！(19)',
      '',
      '',
      '---------------------------',
      '7/20 スケジュールの都合により、一部ステージ時間が変更となりました',
      '',
      '🔻変更後タイムテーブル',
      '・パラレルサイダー',
      '　桃配ステージ 9:45〜10:05',
      '・ポンコツコンポ',
      '　戦国ステージ 19:30〜19:50',
      '',
      '',

      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://pbs.twimg.com/media/GvP9IwHXAAAVvhc?format=jpg&name=medium',
      'https://pbs.twimg.com/media/GvP9IvgaQAAmzfZ?format=jpg&name=medium',
      'https://pbs.twimg.com/media/GvP9IxrWsAAl2ro?format=jpg&name=medium',
      'https://pbs.twimg.com/media/GvP9IxUaQAAAd3U?format=jpg&name=medium',
    ],
  },
  {
    id: 16,
    date: '2025.07.04',
    title: '公式アプリ誕生📱',
    context: [
      '',
      '',
      '関ケ原初‼️',
      'イベント公式アプリが誕生‼️',
      '',
      '👇🏻インストールはこちらから👇🏻',
      'https://app.sekigahara-idolwars.net',
      '',
      '◾️手順',
      '①アプリを開く',
      '②ブラウザから「ホーム画面に追加」で追加する',
      '',
      '',
      '',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: ['https://pbs.twimg.com/media/GvAiyJhWwAAAl1Y?format=jpg&name=large'],
  },
  {
    id: 15,
    date: '2025.07.02',
    title: '関ケ原唄姫合戦サテライトイベント開催決定',
    context: [
      '',
      '',
      '2025年7月19日(土)、7月20日(日)、7月21日(月祝)',
      '',
      '関ケ原唄姫合戦サテライトイベント',
      '〜徳川？豊臣？いやいや岐阜は織田じゃ⚔️〜',
      '',
      '🎪会場：岐阜club-G',
      '',
      '',
      '🎫TIGET 先着予約',
      '',
      '19日 https://tiget.net/events/412437',
      '20日 https://tiget.net/events/412439',
      '21日 https://tiget.net/events/412444',
      '',
      'Aチケット2,500円　当日3,500円　（※D代別途）',
      '',
      '明日7/3(金)20:00〜順次予約受付開始‼️',
      '',
      '',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: ['https://pbs.twimg.com/media/Gu6iXiSWwAAHCGz?format=jpg&name=large'],
  },
  {
    id: 14,
    date: '2025.07.01',
    title: 'ライブタイムテーブル発表!!',
    context: [
      '',
      '',
      'ライブタイムテーブル発表！！',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://pbs.twimg.com/media/Guva_HNbsAAjk8J?format=jpg&name=4096x4096',
      'https://pbs.twimg.com/media/GuvbAaaboAIA_Mk?format=jpg&name=4096x4096',
      'https://pbs.twimg.com/media/GuvbBZTWEAAzoAv?format=jpg&name=4096x4096',
    ],
  },
  {
    id: 13,
    date: '2025.06.13',
    title: '追加布陣・最新出演日発表',
    context: [
      '',
      '',
      '⚔️追加布陣として4組 出陣決定⚔️',
      '',
      'アステリア (20)',
      'ナト☆カン (20)',
      'にっぽんワチャチャ (21)',
      'パラディーク (21)',
      '',
      'シュレーディンガーの犬 さんの出演日程に関しまして、若干変更がございます。',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://pbs.twimg.com/media/GtTzxTnbAAAfv8m?format=jpg&name=4096x4096',
      'https://pbs.twimg.com/media/GtTz265bMAEXPee?format=jpg&name=large',
    ],
  },
  {
    id: 12,
    date: '2025.06.12',
    title: '各出演日発表',
    context: [
      '',
      '',
      '⚔️150組を超える唄姫たちの出演日 解禁⚔️',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: ['https://pbs.twimg.com/media/GtNf6RTasAAyqkZ?format=jpg&name=large'],
  },
  {
    id: 11,
    date: '2025.06.12',
    title: '出演者　第八布陣発表',
    context: [
      '⚔️第八布陣として6組 出陣決定⚔️',
      '',
      '',
      'EYE CANDY',
      'アルテミスの翼',
      'ESTLINK☆',
      'dela',
      'HOT DOG CAT',
      'われらがプワプワプーワプワ',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: ['https://pbs.twimg.com/media/GtNckjja0AA4vxs?format=jpg&name=4096x4096'],
  },
  {
    id: 10,
    date: '2025.06.11',
    title: '⚔️チケット詳細発表⚔️',
    context: ['⚔️チケット詳細発表⚔️', '', '', ''],
    urls: ['https://tiget.net/events/407817', 'https://sekigahara-idolwars.net/ticket'],
    img: ['https://sekigahara-idolwars.net/images/2025/ticket.jpg'],
  },
  {
    id: 9,
    date: '2025.06.11',
    title: '出演者　第七布陣発表',
    context: [
      '⚔️第七布陣として予戦会突破組 出陣決定⚔️',
      '',
      '',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E4%B8%83%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 8,
    date: '2025.06.10',
    title: '出演者　第六布陣発表',
    context: [
      '⚔️第六布陣として20組 出陣決定⚔️',
      '',
      '',
      'AQA',
      'アップアップガールズ（２）',
      'α',
      'OS☆U',
      'Ｏ₂',
      'KAIJU ON THE STAGE',
      'CAL&RES',
      'ジエメイ',
      'JamsCollection',
      'ZUTTOMOTTO',
      'SUPER☆GiRLS',
      'Cent Heaven',
      '蜂蜜★皇帝',
      'パラレルサイダー',
      "Ma'Scar'Piece",
      'MATANAGOYA',
      'みらくらんど',
      'メイビーME',
      'LOVEME',
      'Re:Clash',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E5%85%AD%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 7,
    date: '2025.06.08',
    title: '出演者　第五布陣発表',
    context: [
      '⚔️第五布陣として30組 出陣決定⚔️',
      '',
      '',
      'あくまで天使',
      '雨のち、ハレーション',
      'エラバレシ',
      'ゑんら',
      'オカシリゾート',
      'キミニハネ',
      '逆転ねこぱんちっ！',
      'キュン!?恋堕ちキューピッド',
      'GILTY×GILTY',
      'Glim Assembler',
      'JAPANARIZM',
      '終末のアンセム',
      'Jewel☆Garden',
      '夜宙☆ShiNew’',
      'すーぱーぷーばぁー!!',
      '月に足跡を残した少女達は一体何を見たのか...',
      'ティラミス',
      '天空のシラバス',
      'TENRIN',
      '脳内パステル',
      '蜜兎',
      'Bunny La Crew',
      'ベンジャス！',
      'WT★Egret',
      'Milky＊Sphene',
      'ヤンチャン学園音楽部',
      'LADYBABY',
      'RiNCENT#',
      'Loulouchouchou',
      'わんふぁす！',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E4%BA%94%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 6,
    date: '2025.06.05',
    title: '出演者　第四布陣発表',
    context: [
      '⚔️第四布陣として20組 出陣決定⚔️',
      '',
      '',
      'i-COL',
      'As a Cutie Pomeranian',
      'Ill',
      'AdamLilith',
      '泡沫パーティーズ',
      '仮面女子',
      'きゅ～くる',
      'SAI ²Rium',
      'スポポポポニー',
      'セカモノ',
      'テラテラ',
      'Drug&Drop',
      'ドレスコード',
      'HIGH SPIRITS',
      'HAPPY CREATORS',
      'Panic Monster !n Wonderland',
      'フューチャーサイダー',
      'PrincessGarden-TOKYO-',
      'フルーティー',
      'READY TO KISS',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E5%9B%9B%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 5,
    date: '2025.06.03',
    title: '出演者　第三布陣発表',
    context: [
      '⚔️第三布陣として20組 出陣決定⚔️',
      '',
      '',
      'I MY ME MINE',
      'Alcute！',
      'KOIHAJI',
      'サクヤコノハナ',
      'シークレットシャノワール',
      'SPRISE',
      'テンシンランマン',
      'DREAMING MONSTER',
      '夏空のオリオン',
      'ナナコロビヤオキ',
      'NEO BREAK',
      'Palette Parade',
      'ポラライト',
      'ポンコツコンポ',
      'My_Stage',
      'MEGAFON',
      'Melty BeaR',
      'ゆるめるモ！',
      'Lily wonder',
      'Root mimi',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E4%B8%89%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 4,
    date: '2025.06.01',
    title: '出演者　第二布陣発表',
    context: [
      '⚔️第ニ布陣として20組 出陣決定⚔️',
      '',
      '',
      'iON!',
      'アイドルカレッジ',
      'iLiFE!',
      'THE ENCORE',
      'UtaGe!',
      '可憐なアイボリー',
      '九州女子翼',
      'KRD8',
      'シュレーディンガーの犬',
      'Sweet Alley',
      'SAY-LA',
      'W.ダブルヴィー',
      '手羽先センセーション',
      '点染テンセイ少女。',
      '虹色の飛行少女',
      'ハニースパイスRe.',
      'Peel the Apple',
      'MyDresscode',
      '夜光性アミューズ',
      'Luce Twinkle Wink☆',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E4%BA%8C%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 3,
    date: '2025.05.29',
    title: '出演者　第一布陣発表',
    context: [
      '⚔️第一布陣として15組 出陣決定⚔️',
      '',
      '',
      'アキシブproject',
      'カラフルスクリーム',
      '君に、胸キュン。',
      '煌めき☆アンフォレント',
      'シンデレラ宣言！',
      'SAISON',
      'Task have Fun',
      'なみだ色の消しごむ',
      'のんふぃく！',
      '花いろは',
      'FES☆TIVE',
      'MyDearDarlin’',
      'まねきケチャ',
      'ワンダーウィード 天',
      'わーすた',
      '（五十音順）',
      '',
      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: [],
    img: [
      'https://sekigahara-idolwars.net/images/2025/news/%E9%96%A2%E3%82%B1%E5%8E%9F%E5%94%84%E5%A7%AB%E5%90%88%E6%88%A62025_%E7%AC%AC%E4%B8%80%E5%B8%83%E9%99%A3.jpg',
    ],
  },
  {
    id: 2,
    date: '2025.03.31',
    title: '関ケ原唄姫合戦2025 予戦会 開催決定‼️',
    context: [
      '11回目の関ケ原',
      '新たな夏がやってくる！',
      '',
      '今年も #関ケ原唄姫合戦2025予戦会 開催決定‼️',
      '',
      '＝＝＝＝',
      'SEKIGAHARA IDOL WARS -関ケ原唄姫合戦- 予戦会',
      '2025年5月1日（木）～5月25日（日）',
      '＝＝＝＝',
      '',
      '4月1日（火）〜　予戦会参加アイドルの募集開始💥',
      'エントリーは、以下関ケ原ホームページのエントリーフォームから',

      '',
      '新たな夏の幕開けに相応しい唄姫は',
      '私たちだ。',
    ],
    urls: ['https://sekigahara-idolwars.net/entry'],
    img: ['https://yosen2025.sekigahara-idolwars.net/picture/yosen-20250405.jpeg'],
  },
  {
    id: 1,
    date: '2025.03.26',
    title: '関ケ原唄姫合戦2025　開催決定！！',
    context: [
      '新たな夏がやってくる',
      '',
      '11回目の唄姫合戦は、さらに熱い🔥',
      '#関ケ原唄姫合戦2025 3DAYS開催決定',
      '',
      '-----',
      '2025年7月19日(土),20日(日),21日(月)',
      'SEKIGAHARA IDOL WARS -関ケ原唄姫合戦-',
      'at 桃配運動公園',
      '-----',
      '',
      '#11回目の関ケ原',
      '#新たな夏',
      '#本当の夏',
      '#俺たちの夏',
      '#関ケ原唄姫合戦',
      '',
      '一緒に戦いましょう⚔️',
    ],
    urls: [],
    img: ['https://yosen2025.sekigahara-idolwars.net/picture/yosen-20250405.jpeg'],
  },
]
